.\" gcolorsel.1 - GNOME Color Browser
.\" Copyright 2001  Jochen Voss
.TH gcolorsel 1 "Apr 7 2001" "gnome-utils 1.4.0"
.SH NAME
gcolorsel \- the GNOME Color Browser
.SH SYNOPSIS
.B gcolorsel
.sp
or select
.B Color Browser
from the
.B Utilities
submenu of the Main Menu.
.SH DESCRIPTION
.B GNOME Color Browser
is a utility for selecting screen (i.e., X Window System) color.  The
X Window System comes with many pre-defined colors, from Alice Blue to
Pale Goldenrod to Yellow Green. GNOME Color Browser lets you browse
these colors and select one of them to be used by an application. It
also allows you define your own collection of favorite colors, or find
a pre-defined color most closely matching a given one.

For full documentation see the
.B GNOME Color Browser
online help.

.SH AUTHOR
.B GNOME Color Browser
was written by Tim Gerla and Eric Brayeur.

This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.

.SH SEE ALSO
.BR xcolorsel (1),
.BR showrgb (1x)
