include ../examples.conf 

TARGETS = progressbar 

all: $(TARGETS)

progressbar: progressbar.cc
	$(CXXBUILD)

progressbar2: progressbar2.cc
	$(CXXBUILD)

clean: 
	rm -Rf .libs *.o *.lo core $(TARGETS)

