.TH INTLTOOLIZE 8 "September 09, 2001" "intltool"

.SH NAME
intltoolize \- prepare a package to use intltool

.SH SYNOPSIS
.B "intltoolize"
[
.BR --automake
] [
.BR \-c | --copy
] [
.BR --debug
] [
.BR \-n | --dry-run
] [
.BR \-f | --force
] [
.BR \--help
] [
.BR \--version
]


.SH DESCRIPTION
This prepares a package to use intltool by linking or copying
various files needed by intltool into place for use when building.
Note that you must change your working directory to the top
level directory of the package before running
.B intltoolize.


.SH OPTIONS
.TP
.B \--automake
Work silently and assume that
.B automake
is being used.
.TP
.B \-c, \--copy
Copy files rather than symlinking to them.
.TP
.B \--debug
Enable verbose shell tracing.
.TP
.B \-n, \--dry-run
Print commands rather then executing them.
.TP
.B \-f, \--force
Replace existing files if they exist.
.TP
.B \--help
Show usage and basic help information.
.TP
.B \--version
Show version information.


.SH REPORTING BUGS
Report bugs to http://bugzilla.gnome.org or by sending email
to xml-i18n-tools@gnome.org.

.SH AUTHOR
Darin Adler           <darin@bentspoon.com>
.br
Kenneth Christiansen  <kenneth@gnu.org>
.br
Maciej Stachowiak     <mjs@eazel.com>


.SH SEE ALSO
intltool-merge(8), intltool-prepare(8), intltool-extract(8)
