.TH INTLTOOL-PREPARE 8 "September 09, 2001" "intltool"

.SH NAME
intltool-prepare \- update pot files and merge them with
translation (po) files

.SH SYNOPSIS
.B "intltool-prepare"
[
.BR \-H | --help
] [
.BR \-X | --verbose
] [
.BR \-V | --version
]
.IR KEYWORD


.SH DESCRIPTION
.B intltool-prepare
searches for strings which have been marked for translation in
the various source and header files specified in the file
po/POTFILES, updates the pot files, and merges them with the
translation (po) files. The key \fIKEYWORD\fP is an additional key 
besides Name, Comment, and description.


.SH OPTIONS
.TP
.B \-H, \--help
Show usage and basic help information.
.TP
.B \-X, \--verbose
Be verbose to give the user additional feedback.
.TP
.B \-V, \--version
Show version information.


.SH REPORTING BUGS
Report bugs to http://bugzilla.gnome.org or by sending email
to xml-i18n-tools@gnome.org.

.SH AUTHOR
Darin Adler           <darin@bentspoon.com>
.br
Kenneth Christiansen  <kenneth@gnu.org>
.br
Maciej Stachowiak     <mjs@eazel.com>


.SH SEE ALSO
intltool-toolize(8), intltool-merge(8), intltool-extract(8)
