.TH INTLTOOL-EXTRACT 8 "September 09, 2001" "intltool"

.SH NAME
intltool-extract \- generate header files which can be read by gettext

.SH SYNOPSIS
.B "intltool-extract"
[
.BR --ini-style
] [
.BR \-X | --verbose
] [
.BR \-H | --help
] [
.BR \-V | --version
] [
.BR --xml-style
] [
.BR --scheme-style
]
.IR BLAH


.SH DESCRIPTION
This generates header files from the strings in the specified
input files which gettext can use to merge strings into the pot
file.


.SH OPTIONS
.TP
.B \--ini-style
File is of type gettext/ini.
.TP
.B \-X, \--verbose
Be verbose to give the user additional feedback.
.TP
.B \-H, \--help
Show usage and basic help information.
.TP
.B \-V, \--version
Show version information.
.TP
.B \-O, \--xml-style
File is of type gettext/xml.
.TP
.B \-O, \--scheme-style
File is of type gettext/scheme.

.SH REPORTING BUGS
Report bugs to http://bugzilla.gnome.org or by sending email
to xml-i18n-tools@gnome.org.

.SH AUTHOR
Darin Adler           <darin@bentspoon.com>
.br
Kenneth Christiansen  <kenneth@gnu.org>
.br
Maciej Stachowiak     <mjs@eazel.com>


.SH SEE ALSO
intltoolize(8), intltool-prepare(8), intltool-merge(8)
