.TH INTLTOOL-MERGE 8 "September 09, 2001" "intltool"

.SH NAME
intltool-merge \- merge translated strings into various file 
types such as XML

.SH SYNOPSIS
.B "intltool-merge"
[
.BR \-X | --verbose
] [
.BR \-D | --style-desktop
] [
.BR \-O | --style-xml
] [
.BR \-K | --style-keys
] [
.BR \-H | --help
] [
.BR \-V | --version
]
.IR PO_DIRECTORY
.IR FILENAME
.IR OUTPUT_FILE


.SH DESCRIPTION
Merge translated strings in po files in \fIPO_DIRECTORY\fP 
with the original application file \fIFILENAME\fP, 
and output the file \fIOUTPUT_FILE\fP containing both the original
and the localized strings.


.SH OPTIONS
.TP
.B \-X, \--verbose
Be verbose to give the user additional feedback.
.TP
.B \-D, \--style-desktop
Merge files in desktop style, which is similar to
the Windows .ini file format.
.TP
.B \-O, \--style-xml
Merge files in the XML style, both as attributes and as
raw pcdata.
.TP
.B \-K, \--style-keys
Merge files in the keys style, which is used for metadata.
.TP
.B \-H, \--help
Show usage and basic help information.
.TP
.B \-V, \--version
Show version information.


.SH REPORTING BUGS
Report bugs to http://bugzilla.gnome.org or by sending email
to xml-i18n-tools@gnome.org.

.SH AUTHOR
Darin Adler           <darin@bentspoon.com>
.br
Kenneth Christiansen  <kenneth@gnu.org>
.br
Maciej Stachowiak     <mjs@eazel.com>


.SH SEE ALSO
intltoolize(8), xml-18n-prepare(8), intltool-extract(8)
