/* Generated by build-guile-gtk.  Do not edit. */

#include <libguile.h>
#include <guile-gtk.h>

void gnome_init_guile_glue ();
void sgtk_init_gtk_gtk_glue ();
void sgtk_init_gtk_gdk_glue ();

static void
inner_main (void *closure, int argc, char **argv)
{
  SGTK_REGISTER_GLUE (gnome_init_guile_glue);
  SGTK_REGISTER_GLUE (sgtk_init_gtk_gtk_glue);
  SGTK_REGISTER_GLUE (sgtk_init_gtk_gdk_glue);
  sgtk_shell (argc, argv);
}

int
main (int argc, char **argv)
{
  scm_boot_guile (argc, argv, inner_main, 0);
  return 0; /* never reached */
}
