.\" gcharmap.1 - GNOME Character Map
.\" Copyright 2001  Jochen Voss
.TH gcharmap 1 "Apr 7 2001" "gnome-utils 1.4.0"
.SH NAME
gcharmap \- the GNOME Character Map
.SH SYNOPSIS
.B gcharmap
.sp
or select
.B GNOME Character Map
from the
.B Utilities
submenu of the Main Menu.
.SH DESCRIPTION
.B GNOME Character Map
is a program that allows you to select any character available in your
current font.  With
.BR "GNOME Character Map" ,
you can also use characters that you cannot type with your keybord
(such as "extended ASCII characters", or characters with codes greater
than 127, for example the copyright symbol).

For full documentation see the
.B GNOME Character Map
online help.

.SH AUTHOR
.B GNOME Character Map
was written by Hongli Lai (<hongli@telekabel.nl>).

This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.

.SH SEE ALSO
The
.B GNOME Character Map
Web page
.B http://users.telekabel.nl/hongli/eng/software/gcharmap/index.html
