.\" gless.1 - GNOME less
.\" Copyright 2001  Jochen Voss
.TH gless 1 "Apr 16 2001" "gnome-utils 1.4.0"
.SH NAME
gless \- a program for viewing text files
.SH SYNOPSIS
.B gless
.sp
or select
.B Text File Viewer
from the
.B Utilities
submenu of the Main Menu.
.SH DESCRIPTION
.B Gless
is a program for viewing text files, similar to the standard unix
command
.I less.

For full documentation see the
.B Gless
online help.

.SH AUTHOR
.B Gless
was written by Havoc Pennington (<hp@redhat.com>).

This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.

.SH SEE ALSO
.BR less (1),
.BR xless (1x)
