/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "control-center.h"

#if ( (TC_IMPL_TC_GNOME_capplet_0 == 'c') \
&& (TC_IMPL_TC_GNOME_capplet_1 == 'o') \
&& (TC_IMPL_TC_GNOME_capplet_2 == 'n') \
&& (TC_IMPL_TC_GNOME_capplet_3 == 't') \
&& (TC_IMPL_TC_GNOME_capplet_4 == 'r') \
&& (TC_IMPL_TC_GNOME_capplet_5 == 'o') \
&& (TC_IMPL_TC_GNOME_capplet_6 == 'l') \
&& (TC_IMPL_TC_GNOME_capplet_7 == '_') \
&& (TC_IMPL_TC_GNOME_capplet_8 == 'c') \
&& (TC_IMPL_TC_GNOME_capplet_9 == 'e') \
&& (TC_IMPL_TC_GNOME_capplet_10 == 'n') \
&& (TC_IMPL_TC_GNOME_capplet_11 == 't') \
&& (TC_IMPL_TC_GNOME_capplet_12 == 'e') \
&& (TC_IMPL_TC_GNOME_capplet_13 == 'r') \
) && !defined(TC_DEF_TC_GNOME_capplet)
#define TC_DEF_TC_GNOME_capplet 1
const struct CORBA_TypeCode_struct TC_GNOME_capplet_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "capplet", "IDL:GNOME/capplet:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_control_center_0 == 'c') \
&& (TC_IMPL_TC_GNOME_control_center_1 == 'o') \
&& (TC_IMPL_TC_GNOME_control_center_2 == 'n') \
&& (TC_IMPL_TC_GNOME_control_center_3 == 't') \
&& (TC_IMPL_TC_GNOME_control_center_4 == 'r') \
&& (TC_IMPL_TC_GNOME_control_center_5 == 'o') \
&& (TC_IMPL_TC_GNOME_control_center_6 == 'l') \
&& (TC_IMPL_TC_GNOME_control_center_7 == '_') \
&& (TC_IMPL_TC_GNOME_control_center_8 == 'c') \
&& (TC_IMPL_TC_GNOME_control_center_9 == 'e') \
&& (TC_IMPL_TC_GNOME_control_center_10 == 'n') \
&& (TC_IMPL_TC_GNOME_control_center_11 == 't') \
&& (TC_IMPL_TC_GNOME_control_center_12 == 'e') \
&& (TC_IMPL_TC_GNOME_control_center_13 == 'r') \
) && !defined(TC_DEF_TC_GNOME_control_center)
#define TC_DEF_TC_GNOME_control_center 1
const struct CORBA_TypeCode_struct TC_GNOME_control_center_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "control_center", "IDL:GNOME/control_center:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long GNOME_capplet__classid = 0;
CORBA_unsigned_long GNOME_control_center__classid = 0;
