/* device_labels_linux.h
 * This is a stub file, generated by device_labels_linux.sed
 * from linux/soundcard.h kernel include. */

#error This file is i18n stub file and cannot be included!

           SOUND_DEVICE_LABELS	{N_("Vol  "), N_("Bass "), N_("Trebl"), N_("Synth"), N_("Pcm  "), N_("Spkr "), N_("Line "), \
				 N_("Mic  "), N_("CD   "), N_("Mix  "), N_("Pcm2 "), N_("Rec  "), N_("IGain"), N_("OGain"), \
				 N_("Line1"), N_("Line2"), N_("Line3"), N_("Digital1"), N_("Digital2"), N_("Digital3"), \
				 N_("PhoneIn"), N_("PhoneOut"), N_("Video"), N_("Radio"), N_("Monitor")}
