/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "everything.h"

#if ( (TC_IMPL_TC_test_Colour_0 == 'e') \
&& (TC_IMPL_TC_test_Colour_1 == 'v') \
&& (TC_IMPL_TC_test_Colour_2 == 'e') \
&& (TC_IMPL_TC_test_Colour_3 == 'r') \
&& (TC_IMPL_TC_test_Colour_4 == 'y') \
&& (TC_IMPL_TC_test_Colour_5 == 't') \
&& (TC_IMPL_TC_test_Colour_6 == 'h') \
&& (TC_IMPL_TC_test_Colour_7 == 'i') \
&& (TC_IMPL_TC_test_Colour_8 == 'n') \
&& (TC_IMPL_TC_test_Colour_9 == 'g') \
) && !defined(TC_DEF_TC_test_Colour)
#define TC_DEF_TC_test_Colour 1
static const char *anon_subnames_array1[] = { "red", "green", "blue" };
const struct CORBA_TypeCode_struct TC_test_Colour_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_enum, "Colour", "IDL:orbit/test/Colour:1.0",
   0, 3,
   (const char **) anon_subnames_array1,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_TestFactory_0 == 'e') \
&& (TC_IMPL_TC_test_TestFactory_1 == 'v') \
&& (TC_IMPL_TC_test_TestFactory_2 == 'e') \
&& (TC_IMPL_TC_test_TestFactory_3 == 'r') \
&& (TC_IMPL_TC_test_TestFactory_4 == 'y') \
&& (TC_IMPL_TC_test_TestFactory_5 == 't') \
&& (TC_IMPL_TC_test_TestFactory_6 == 'h') \
&& (TC_IMPL_TC_test_TestFactory_7 == 'i') \
&& (TC_IMPL_TC_test_TestFactory_8 == 'n') \
&& (TC_IMPL_TC_test_TestFactory_9 == 'g') \
) && !defined(TC_DEF_TC_test_TestFactory)
#define TC_DEF_TC_test_TestFactory 1
const struct CORBA_TypeCode_struct TC_test_TestFactory_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "TestFactory", "IDL:orbit/test/TestFactory:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_TransientObj_0 == 'e') \
&& (TC_IMPL_TC_test_TransientObj_1 == 'v') \
&& (TC_IMPL_TC_test_TransientObj_2 == 'e') \
&& (TC_IMPL_TC_test_TransientObj_3 == 'r') \
&& (TC_IMPL_TC_test_TransientObj_4 == 'y') \
&& (TC_IMPL_TC_test_TransientObj_5 == 't') \
&& (TC_IMPL_TC_test_TransientObj_6 == 'h') \
&& (TC_IMPL_TC_test_TransientObj_7 == 'i') \
&& (TC_IMPL_TC_test_TransientObj_8 == 'n') \
&& (TC_IMPL_TC_test_TransientObj_9 == 'g') \
) && !defined(TC_DEF_TC_test_TransientObj)
#define TC_DEF_TC_test_TransientObj 1
const struct CORBA_TypeCode_struct TC_test_TransientObj_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "TransientObj", "IDL:orbit/test/TransientObj:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_FixedLengthStruct_0 == 'e') \
&& (TC_IMPL_TC_test_FixedLengthStruct_1 == 'v') \
&& (TC_IMPL_TC_test_FixedLengthStruct_2 == 'e') \
&& (TC_IMPL_TC_test_FixedLengthStruct_3 == 'r') \
&& (TC_IMPL_TC_test_FixedLengthStruct_4 == 'y') \
&& (TC_IMPL_TC_test_FixedLengthStruct_5 == 't') \
&& (TC_IMPL_TC_test_FixedLengthStruct_6 == 'h') \
&& (TC_IMPL_TC_test_FixedLengthStruct_7 == 'i') \
&& (TC_IMPL_TC_test_FixedLengthStruct_8 == 'n') \
&& (TC_IMPL_TC_test_FixedLengthStruct_9 == 'g') \
) && !defined(TC_DEF_TC_test_FixedLengthStruct)
#define TC_DEF_TC_test_FixedLengthStruct 1
static const char *anon_subnames_array13[] = { "a" };
static const CORBA_TypeCode anon_subtypes_array14[] =
   { (CORBA_TypeCode) & TC_CORBA_short_struct };
const struct CORBA_TypeCode_struct TC_test_FixedLengthStruct_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_struct, "FixedLengthStruct",
      "IDL:orbit/test/FixedLengthStruct:1.0",
   0, 1,
   (const char **) anon_subnames_array13,
   (CORBA_TypeCode *) anon_subtypes_array14,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_VariableLengthStruct_0 == 'e') \
&& (TC_IMPL_TC_test_VariableLengthStruct_1 == 'v') \
&& (TC_IMPL_TC_test_VariableLengthStruct_2 == 'e') \
&& (TC_IMPL_TC_test_VariableLengthStruct_3 == 'r') \
&& (TC_IMPL_TC_test_VariableLengthStruct_4 == 'y') \
&& (TC_IMPL_TC_test_VariableLengthStruct_5 == 't') \
&& (TC_IMPL_TC_test_VariableLengthStruct_6 == 'h') \
&& (TC_IMPL_TC_test_VariableLengthStruct_7 == 'i') \
&& (TC_IMPL_TC_test_VariableLengthStruct_8 == 'n') \
&& (TC_IMPL_TC_test_VariableLengthStruct_9 == 'g') \
) && !defined(TC_DEF_TC_test_VariableLengthStruct)
#define TC_DEF_TC_test_VariableLengthStruct 1
static const char *anon_subnames_array17[] = { "a" };
static const CORBA_TypeCode anon_subtypes_array18[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_test_VariableLengthStruct_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_struct, "VariableLengthStruct",
      "IDL:orbit/test/VariableLengthStruct:1.0",
   0, 1,
   (const char **) anon_subnames_array17,
   (CORBA_TypeCode *) anon_subtypes_array18,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_CompoundStruct_0 == 'e') \
&& (TC_IMPL_TC_test_CompoundStruct_1 == 'v') \
&& (TC_IMPL_TC_test_CompoundStruct_2 == 'e') \
&& (TC_IMPL_TC_test_CompoundStruct_3 == 'r') \
&& (TC_IMPL_TC_test_CompoundStruct_4 == 'y') \
&& (TC_IMPL_TC_test_CompoundStruct_5 == 't') \
&& (TC_IMPL_TC_test_CompoundStruct_6 == 'h') \
&& (TC_IMPL_TC_test_CompoundStruct_7 == 'i') \
&& (TC_IMPL_TC_test_CompoundStruct_8 == 'n') \
&& (TC_IMPL_TC_test_CompoundStruct_9 == 'g') \
) && !defined(TC_DEF_TC_test_CompoundStruct)
#define TC_DEF_TC_test_CompoundStruct 1
static const char *anon_subnames_array21[] = { "a" };
static const CORBA_TypeCode anon_subtypes_array22[] =
   { (CORBA_TypeCode) & TC_test_VariableLengthStruct_struct };
const struct CORBA_TypeCode_struct TC_test_CompoundStruct_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_struct, "CompoundStruct", "IDL:orbit/test/CompoundStruct:1.0",
   0, 1,
   (const char **) anon_subnames_array21,
   (CORBA_TypeCode *) anon_subtypes_array22,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_StructServer_0 == 'e') \
&& (TC_IMPL_TC_test_StructServer_1 == 'v') \
&& (TC_IMPL_TC_test_StructServer_2 == 'e') \
&& (TC_IMPL_TC_test_StructServer_3 == 'r') \
&& (TC_IMPL_TC_test_StructServer_4 == 'y') \
&& (TC_IMPL_TC_test_StructServer_5 == 't') \
&& (TC_IMPL_TC_test_StructServer_6 == 'h') \
&& (TC_IMPL_TC_test_StructServer_7 == 'i') \
&& (TC_IMPL_TC_test_StructServer_8 == 'n') \
&& (TC_IMPL_TC_test_StructServer_9 == 'g') \
) && !defined(TC_DEF_TC_test_StructServer)
#define TC_DEF_TC_test_StructServer 1
const struct CORBA_TypeCode_struct TC_test_StructServer_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "StructServer", "IDL:orbit/test/StructServer:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'y') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array30[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array30,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'y') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array39[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array39,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_StrSeq_0 == 'e') \
&& (TC_IMPL_TC_test_StrSeq_1 == 'v') \
&& (TC_IMPL_TC_test_StrSeq_2 == 'e') \
&& (TC_IMPL_TC_test_StrSeq_3 == 'r') \
&& (TC_IMPL_TC_test_StrSeq_4 == 'y') \
&& (TC_IMPL_TC_test_StrSeq_5 == 't') \
&& (TC_IMPL_TC_test_StrSeq_6 == 'h') \
&& (TC_IMPL_TC_test_StrSeq_7 == 'i') \
&& (TC_IMPL_TC_test_StrSeq_8 == 'n') \
&& (TC_IMPL_TC_test_StrSeq_9 == 'g') \
) && !defined(TC_DEF_TC_test_StrSeq)
#define TC_DEF_TC_test_StrSeq 1
static const CORBA_TypeCode anon_subtypes_array43[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_test_StrSeq_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "StrSeq", "IDL:orbit/test/StrSeq:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array43,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_0 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_1 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_3 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_4 == 'y') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_5 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_6 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_7 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_9 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_test_CompoundStruct)
#define TC_DEF_TC_CORBA_sequence_test_CompoundStruct 1
static const CORBA_TypeCode anon_subtypes_array47[] =
   { (CORBA_TypeCode) & TC_test_CompoundStruct_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_test_CompoundStruct_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   2, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array47,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_0 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_1 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_3 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_4 == 'y') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_5 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_6 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_7 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_test_CompoundStruct_9 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_test_CompoundStruct)
#define TC_DEF_TC_CORBA_sequence_test_CompoundStruct 1
static const CORBA_TypeCode anon_subtypes_array56[] =
   { (CORBA_TypeCode) & TC_test_CompoundStruct_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_test_CompoundStruct_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   2, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array56,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_BoundedStructSeq_0 == 'e') \
&& (TC_IMPL_TC_test_BoundedStructSeq_1 == 'v') \
&& (TC_IMPL_TC_test_BoundedStructSeq_2 == 'e') \
&& (TC_IMPL_TC_test_BoundedStructSeq_3 == 'r') \
&& (TC_IMPL_TC_test_BoundedStructSeq_4 == 'y') \
&& (TC_IMPL_TC_test_BoundedStructSeq_5 == 't') \
&& (TC_IMPL_TC_test_BoundedStructSeq_6 == 'h') \
&& (TC_IMPL_TC_test_BoundedStructSeq_7 == 'i') \
&& (TC_IMPL_TC_test_BoundedStructSeq_8 == 'n') \
&& (TC_IMPL_TC_test_BoundedStructSeq_9 == 'g') \
) && !defined(TC_DEF_TC_test_BoundedStructSeq)
#define TC_DEF_TC_test_BoundedStructSeq 1
static const CORBA_TypeCode anon_subtypes_array60[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_test_CompoundStruct_struct };
const struct CORBA_TypeCode_struct TC_test_BoundedStructSeq_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "BoundedStructSeq", "IDL:orbit/test/BoundedStructSeq:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array60,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_long_0 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_1 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_3 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_4 == 'y') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_5 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_6 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_7 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_9 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_long)
#define TC_DEF_TC_CORBA_sequence_CORBA_long 1
static const CORBA_TypeCode anon_subtypes_array64[] =
   { (CORBA_TypeCode) & TC_CORBA_long_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_long_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   2, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array64,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_long_0 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_1 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_3 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_4 == 'y') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_5 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_6 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_7 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_9 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_long)
#define TC_DEF_TC_CORBA_sequence_CORBA_long 1
static const CORBA_TypeCode anon_subtypes_array73[] =
   { (CORBA_TypeCode) & TC_CORBA_long_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_long_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   2, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array73,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_BoundedLongSeq_0 == 'e') \
&& (TC_IMPL_TC_test_BoundedLongSeq_1 == 'v') \
&& (TC_IMPL_TC_test_BoundedLongSeq_2 == 'e') \
&& (TC_IMPL_TC_test_BoundedLongSeq_3 == 'r') \
&& (TC_IMPL_TC_test_BoundedLongSeq_4 == 'y') \
&& (TC_IMPL_TC_test_BoundedLongSeq_5 == 't') \
&& (TC_IMPL_TC_test_BoundedLongSeq_6 == 'h') \
&& (TC_IMPL_TC_test_BoundedLongSeq_7 == 'i') \
&& (TC_IMPL_TC_test_BoundedLongSeq_8 == 'n') \
&& (TC_IMPL_TC_test_BoundedLongSeq_9 == 'g') \
) && !defined(TC_DEF_TC_test_BoundedLongSeq)
#define TC_DEF_TC_test_BoundedLongSeq 1
static const CORBA_TypeCode anon_subtypes_array77[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_long_struct };
const struct CORBA_TypeCode_struct TC_test_BoundedLongSeq_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "BoundedLongSeq", "IDL:orbit/test/BoundedLongSeq:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array77,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_long_0 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_1 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_3 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_4 == 'y') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_5 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_6 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_7 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_9 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_long)
#define TC_DEF_TC_CORBA_sequence_CORBA_long 1
static const CORBA_TypeCode anon_subtypes_array81[] =
   { (CORBA_TypeCode) & TC_CORBA_long_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_long_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array81,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_long_0 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_1 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_3 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_4 == 'y') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_5 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_6 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_7 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_9 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_long)
#define TC_DEF_TC_CORBA_sequence_CORBA_long 1
static const CORBA_TypeCode anon_subtypes_array90[] =
   { (CORBA_TypeCode) & TC_CORBA_long_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_long_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array90,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_LongSeq_0 == 'e') \
&& (TC_IMPL_TC_test_LongSeq_1 == 'v') \
&& (TC_IMPL_TC_test_LongSeq_2 == 'e') \
&& (TC_IMPL_TC_test_LongSeq_3 == 'r') \
&& (TC_IMPL_TC_test_LongSeq_4 == 'y') \
&& (TC_IMPL_TC_test_LongSeq_5 == 't') \
&& (TC_IMPL_TC_test_LongSeq_6 == 'h') \
&& (TC_IMPL_TC_test_LongSeq_7 == 'i') \
&& (TC_IMPL_TC_test_LongSeq_8 == 'n') \
&& (TC_IMPL_TC_test_LongSeq_9 == 'g') \
) && !defined(TC_DEF_TC_test_LongSeq)
#define TC_DEF_TC_test_LongSeq 1
static const CORBA_TypeCode anon_subtypes_array94[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_long_struct };
const struct CORBA_TypeCode_struct TC_test_LongSeq_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "LongSeq", "IDL:orbit/test/LongSeq:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array94,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_test_StrSeq_0 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_1 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_3 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_4 == 'y') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_5 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_6 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_7 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_9 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_test_StrSeq)
#define TC_DEF_TC_CORBA_sequence_test_StrSeq 1
static const CORBA_TypeCode anon_subtypes_array98[] =
   { (CORBA_TypeCode) & TC_test_StrSeq_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_test_StrSeq_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array98,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_test_StrSeq_0 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_1 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_3 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_4 == 'y') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_5 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_6 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_7 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_test_StrSeq_9 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_test_StrSeq)
#define TC_DEF_TC_CORBA_sequence_test_StrSeq 1
static const CORBA_TypeCode anon_subtypes_array107[] =
   { (CORBA_TypeCode) & TC_test_StrSeq_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_test_StrSeq_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array107,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_StrSeqSeq_0 == 'e') \
&& (TC_IMPL_TC_test_StrSeqSeq_1 == 'v') \
&& (TC_IMPL_TC_test_StrSeqSeq_2 == 'e') \
&& (TC_IMPL_TC_test_StrSeqSeq_3 == 'r') \
&& (TC_IMPL_TC_test_StrSeqSeq_4 == 'y') \
&& (TC_IMPL_TC_test_StrSeqSeq_5 == 't') \
&& (TC_IMPL_TC_test_StrSeqSeq_6 == 'h') \
&& (TC_IMPL_TC_test_StrSeqSeq_7 == 'i') \
&& (TC_IMPL_TC_test_StrSeqSeq_8 == 'n') \
&& (TC_IMPL_TC_test_StrSeqSeq_9 == 'g') \
) && !defined(TC_DEF_TC_test_StrSeqSeq)
#define TC_DEF_TC_test_StrSeqSeq 1
static const CORBA_TypeCode anon_subtypes_array111[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_test_StrSeq_struct };
const struct CORBA_TypeCode_struct TC_test_StrSeqSeq_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "StrSeqSeq", "IDL:orbit/test/StrSeqSeq:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array111,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_any_0 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_1 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_3 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_4 == 'y') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_5 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_6 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_7 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_9 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_any)
#define TC_DEF_TC_CORBA_sequence_CORBA_any 1
static const CORBA_TypeCode anon_subtypes_array115[] =
   { (CORBA_TypeCode) & TC_CORBA_any_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_any_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array115,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_any_0 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_1 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_3 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_4 == 'y') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_5 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_6 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_7 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_any_9 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_any)
#define TC_DEF_TC_CORBA_sequence_CORBA_any 1
static const CORBA_TypeCode anon_subtypes_array124[] =
   { (CORBA_TypeCode) & TC_CORBA_any_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_any_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array124,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_AnySeq_0 == 'e') \
&& (TC_IMPL_TC_test_AnySeq_1 == 'v') \
&& (TC_IMPL_TC_test_AnySeq_2 == 'e') \
&& (TC_IMPL_TC_test_AnySeq_3 == 'r') \
&& (TC_IMPL_TC_test_AnySeq_4 == 'y') \
&& (TC_IMPL_TC_test_AnySeq_5 == 't') \
&& (TC_IMPL_TC_test_AnySeq_6 == 'h') \
&& (TC_IMPL_TC_test_AnySeq_7 == 'i') \
&& (TC_IMPL_TC_test_AnySeq_8 == 'n') \
&& (TC_IMPL_TC_test_AnySeq_9 == 'g') \
) && !defined(TC_DEF_TC_test_AnySeq)
#define TC_DEF_TC_test_AnySeq 1
static const CORBA_TypeCode anon_subtypes_array128[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_any_struct };
const struct CORBA_TypeCode_struct TC_test_AnySeq_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "AnySeq", "IDL:orbit/test/AnySeq:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array128,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_StructWithSequenceInIt_0 == 'e') \
&& (TC_IMPL_TC_test_StructWithSequenceInIt_1 == 'v') \
&& (TC_IMPL_TC_test_StructWithSequenceInIt_2 == 'e') \
&& (TC_IMPL_TC_test_StructWithSequenceInIt_3 == 'r') \
&& (TC_IMPL_TC_test_StructWithSequenceInIt_4 == 'y') \
&& (TC_IMPL_TC_test_StructWithSequenceInIt_5 == 't') \
&& (TC_IMPL_TC_test_StructWithSequenceInIt_6 == 'h') \
&& (TC_IMPL_TC_test_StructWithSequenceInIt_7 == 'i') \
&& (TC_IMPL_TC_test_StructWithSequenceInIt_8 == 'n') \
&& (TC_IMPL_TC_test_StructWithSequenceInIt_9 == 'g') \
) && !defined(TC_DEF_TC_test_StructWithSequenceInIt)
#define TC_DEF_TC_test_StructWithSequenceInIt 1
static const char *anon_subnames_array131[] = { "theSeq" };
static const CORBA_TypeCode anon_subtypes_array132[] =
   { (CORBA_TypeCode) & TC_test_StrSeqSeq_struct };
const struct CORBA_TypeCode_struct TC_test_StructWithSequenceInIt_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_struct, "StructWithSequenceInIt",
      "IDL:orbit/test/StructWithSequenceInIt:1.0",
   0, 1,
   (const char **) anon_subnames_array131,
   (CORBA_TypeCode *) anon_subtypes_array132,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_SequenceServer_0 == 'e') \
&& (TC_IMPL_TC_test_SequenceServer_1 == 'v') \
&& (TC_IMPL_TC_test_SequenceServer_2 == 'e') \
&& (TC_IMPL_TC_test_SequenceServer_3 == 'r') \
&& (TC_IMPL_TC_test_SequenceServer_4 == 'y') \
&& (TC_IMPL_TC_test_SequenceServer_5 == 't') \
&& (TC_IMPL_TC_test_SequenceServer_6 == 'h') \
&& (TC_IMPL_TC_test_SequenceServer_7 == 'i') \
&& (TC_IMPL_TC_test_SequenceServer_8 == 'n') \
&& (TC_IMPL_TC_test_SequenceServer_9 == 'g') \
) && !defined(TC_DEF_TC_test_SequenceServer)
#define TC_DEF_TC_test_SequenceServer 1
const struct CORBA_TypeCode_struct TC_test_SequenceServer_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "SequenceServer", "IDL:orbit/test/SequenceServer:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_AnEnum_0 == 'e') \
&& (TC_IMPL_TC_test_AnEnum_1 == 'v') \
&& (TC_IMPL_TC_test_AnEnum_2 == 'e') \
&& (TC_IMPL_TC_test_AnEnum_3 == 'r') \
&& (TC_IMPL_TC_test_AnEnum_4 == 'y') \
&& (TC_IMPL_TC_test_AnEnum_5 == 't') \
&& (TC_IMPL_TC_test_AnEnum_6 == 'h') \
&& (TC_IMPL_TC_test_AnEnum_7 == 'i') \
&& (TC_IMPL_TC_test_AnEnum_8 == 'n') \
&& (TC_IMPL_TC_test_AnEnum_9 == 'g') \
) && !defined(TC_DEF_TC_test_AnEnum)
#define TC_DEF_TC_test_AnEnum 1
static const char *anon_subnames_array139[] =
   { "ENUM_IN", "ENUM_INOUT_IN", "ENUM_INOUT_OUT", "ENUM_OUT", "ENUM_RETN" };
const struct CORBA_TypeCode_struct TC_test_AnEnum_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_enum, "AnEnum", "IDL:orbit/test/AnEnum:1.0",
   0, 5,
   (const char **) anon_subnames_array139,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_TestException_0 == 'e') \
&& (TC_IMPL_TC_test_TestException_1 == 'v') \
&& (TC_IMPL_TC_test_TestException_2 == 'e') \
&& (TC_IMPL_TC_test_TestException_3 == 'r') \
&& (TC_IMPL_TC_test_TestException_4 == 'y') \
&& (TC_IMPL_TC_test_TestException_5 == 't') \
&& (TC_IMPL_TC_test_TestException_6 == 'h') \
&& (TC_IMPL_TC_test_TestException_7 == 'i') \
&& (TC_IMPL_TC_test_TestException_8 == 'n') \
&& (TC_IMPL_TC_test_TestException_9 == 'g') \
) && !defined(TC_DEF_TC_test_TestException)
#define TC_DEF_TC_test_TestException 1
static const char *anon_subnames_array143[] =
   { "reason", "number", "aseq", "factory" };
static const CORBA_TypeCode anon_subtypes_array144[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
(CORBA_TypeCode) & TC_CORBA_long_struct, (CORBA_TypeCode) & TC_test_LongSeq_struct, (CORBA_TypeCode) & TC_Object_struct };
const struct CORBA_TypeCode_struct TC_test_TestException_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "TestException", "IDL:orbit/test/TestException:1.0",
   0, 4,
   (const char **) anon_subnames_array143,
   (CORBA_TypeCode *) anon_subtypes_array144,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_LongArray_0 == 'e') \
&& (TC_IMPL_TC_test_LongArray_1 == 'v') \
&& (TC_IMPL_TC_test_LongArray_2 == 'e') \
&& (TC_IMPL_TC_test_LongArray_3 == 'r') \
&& (TC_IMPL_TC_test_LongArray_4 == 'y') \
&& (TC_IMPL_TC_test_LongArray_5 == 't') \
&& (TC_IMPL_TC_test_LongArray_6 == 'h') \
&& (TC_IMPL_TC_test_LongArray_7 == 'i') \
&& (TC_IMPL_TC_test_LongArray_8 == 'n') \
&& (TC_IMPL_TC_test_LongArray_9 == 'g') \
) && !defined(TC_DEF_TC_test_LongArray)
#define TC_DEF_TC_test_LongArray 1
static const CORBA_TypeCode anon_subtypes_array158[] =
   { (CORBA_TypeCode) & TC_CORBA_long_struct };
static const struct CORBA_TypeCode_struct anonTC_155_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_array, NULL, NULL,
   2, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array158,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
static const CORBA_TypeCode anon_subtypes_array153[] =
   { (CORBA_TypeCode) & anonTC_155_struct };
const struct CORBA_TypeCode_struct TC_test_LongArray_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "LongArray", "IDL:orbit/test/LongArray:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array153,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_StrArray_0 == 'e') \
&& (TC_IMPL_TC_test_StrArray_1 == 'v') \
&& (TC_IMPL_TC_test_StrArray_2 == 'e') \
&& (TC_IMPL_TC_test_StrArray_3 == 'r') \
&& (TC_IMPL_TC_test_StrArray_4 == 'y') \
&& (TC_IMPL_TC_test_StrArray_5 == 't') \
&& (TC_IMPL_TC_test_StrArray_6 == 'h') \
&& (TC_IMPL_TC_test_StrArray_7 == 'i') \
&& (TC_IMPL_TC_test_StrArray_8 == 'n') \
&& (TC_IMPL_TC_test_StrArray_9 == 'g') \
) && !defined(TC_DEF_TC_test_StrArray)
#define TC_DEF_TC_test_StrArray 1
static const CORBA_TypeCode anon_subtypes_array172[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
static const struct CORBA_TypeCode_struct anonTC_169_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_array, NULL, NULL,
   2, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array172,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
static const CORBA_TypeCode anon_subtypes_array167[] =
   { (CORBA_TypeCode) & anonTC_169_struct };
const struct CORBA_TypeCode_struct TC_test_StrArray_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "StrArray", "IDL:orbit/test/StrArray:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array167,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_StrArrayMultiDimensional_0 == 'e') \
&& (TC_IMPL_TC_test_StrArrayMultiDimensional_1 == 'v') \
&& (TC_IMPL_TC_test_StrArrayMultiDimensional_2 == 'e') \
&& (TC_IMPL_TC_test_StrArrayMultiDimensional_3 == 'r') \
&& (TC_IMPL_TC_test_StrArrayMultiDimensional_4 == 'y') \
&& (TC_IMPL_TC_test_StrArrayMultiDimensional_5 == 't') \
&& (TC_IMPL_TC_test_StrArrayMultiDimensional_6 == 'h') \
&& (TC_IMPL_TC_test_StrArrayMultiDimensional_7 == 'i') \
&& (TC_IMPL_TC_test_StrArrayMultiDimensional_8 == 'n') \
&& (TC_IMPL_TC_test_StrArrayMultiDimensional_9 == 'g') \
) && !defined(TC_DEF_TC_test_StrArrayMultiDimensional)
#define TC_DEF_TC_test_StrArrayMultiDimensional 1
static const CORBA_TypeCode anon_subtypes_array196[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
static const struct CORBA_TypeCode_struct anonTC_193_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_array, NULL, NULL,
   5, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array196,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
static const CORBA_TypeCode anon_subtypes_array191[] =
   { (CORBA_TypeCode) & anonTC_193_struct };
static const struct CORBA_TypeCode_struct anonTC_188_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_array, NULL, NULL,
   3, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array191,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
static const CORBA_TypeCode anon_subtypes_array186[] =
   { (CORBA_TypeCode) & anonTC_188_struct };
static const struct CORBA_TypeCode_struct anonTC_183_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_array, NULL, NULL,
   2, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array186,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
static const CORBA_TypeCode anon_subtypes_array181[] =
   { (CORBA_TypeCode) & anonTC_183_struct };
const struct CORBA_TypeCode_struct TC_test_StrArrayMultiDimensional_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "StrArrayMultiDimensional",
      "IDL:orbit/test/StrArrayMultiDimensional:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array181,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_VariableLengthStructArray_0 == 'e') \
&& (TC_IMPL_TC_test_VariableLengthStructArray_1 == 'v') \
&& (TC_IMPL_TC_test_VariableLengthStructArray_2 == 'e') \
&& (TC_IMPL_TC_test_VariableLengthStructArray_3 == 'r') \
&& (TC_IMPL_TC_test_VariableLengthStructArray_4 == 'y') \
&& (TC_IMPL_TC_test_VariableLengthStructArray_5 == 't') \
&& (TC_IMPL_TC_test_VariableLengthStructArray_6 == 'h') \
&& (TC_IMPL_TC_test_VariableLengthStructArray_7 == 'i') \
&& (TC_IMPL_TC_test_VariableLengthStructArray_8 == 'n') \
&& (TC_IMPL_TC_test_VariableLengthStructArray_9 == 'g') \
) && !defined(TC_DEF_TC_test_VariableLengthStructArray)
#define TC_DEF_TC_test_VariableLengthStructArray 1
static const CORBA_TypeCode anon_subtypes_array210[] =
   { (CORBA_TypeCode) & TC_test_VariableLengthStruct_struct };
static const struct CORBA_TypeCode_struct anonTC_207_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_array, NULL, NULL,
   2, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array210,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
static const CORBA_TypeCode anon_subtypes_array205[] =
   { (CORBA_TypeCode) & anonTC_207_struct };
const struct CORBA_TypeCode_struct TC_test_VariableLengthStructArray_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "VariableLengthStructArray",
      "IDL:orbit/test/VariableLengthStructArray:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array205,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_ArrayServer_0 == 'e') \
&& (TC_IMPL_TC_test_ArrayServer_1 == 'v') \
&& (TC_IMPL_TC_test_ArrayServer_2 == 'e') \
&& (TC_IMPL_TC_test_ArrayServer_3 == 'r') \
&& (TC_IMPL_TC_test_ArrayServer_4 == 'y') \
&& (TC_IMPL_TC_test_ArrayServer_5 == 't') \
&& (TC_IMPL_TC_test_ArrayServer_6 == 'h') \
&& (TC_IMPL_TC_test_ArrayServer_7 == 'i') \
&& (TC_IMPL_TC_test_ArrayServer_8 == 'n') \
&& (TC_IMPL_TC_test_ArrayServer_9 == 'g') \
) && !defined(TC_DEF_TC_test_ArrayServer)
#define TC_DEF_TC_test_ArrayServer 1
const struct CORBA_TypeCode_struct TC_test_ArrayServer_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "ArrayServer", "IDL:orbit/test/ArrayServer:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_BasicServer_0 == 'e') \
&& (TC_IMPL_TC_test_BasicServer_1 == 'v') \
&& (TC_IMPL_TC_test_BasicServer_2 == 'e') \
&& (TC_IMPL_TC_test_BasicServer_3 == 'r') \
&& (TC_IMPL_TC_test_BasicServer_4 == 'y') \
&& (TC_IMPL_TC_test_BasicServer_5 == 't') \
&& (TC_IMPL_TC_test_BasicServer_6 == 'h') \
&& (TC_IMPL_TC_test_BasicServer_7 == 'i') \
&& (TC_IMPL_TC_test_BasicServer_8 == 'n') \
&& (TC_IMPL_TC_test_BasicServer_9 == 'g') \
) && !defined(TC_DEF_TC_test_BasicServer)
#define TC_DEF_TC_test_BasicServer 1
const struct CORBA_TypeCode_struct TC_test_BasicServer_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "BasicServer", "IDL:orbit/test/BasicServer:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_BaseServer_0 == 'e') \
&& (TC_IMPL_TC_test_BaseServer_1 == 'v') \
&& (TC_IMPL_TC_test_BaseServer_2 == 'e') \
&& (TC_IMPL_TC_test_BaseServer_3 == 'r') \
&& (TC_IMPL_TC_test_BaseServer_4 == 'y') \
&& (TC_IMPL_TC_test_BaseServer_5 == 't') \
&& (TC_IMPL_TC_test_BaseServer_6 == 'h') \
&& (TC_IMPL_TC_test_BaseServer_7 == 'i') \
&& (TC_IMPL_TC_test_BaseServer_8 == 'n') \
&& (TC_IMPL_TC_test_BaseServer_9 == 'g') \
) && !defined(TC_DEF_TC_test_BaseServer)
#define TC_DEF_TC_test_BaseServer 1
const struct CORBA_TypeCode_struct TC_test_BaseServer_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "BaseServer", "IDL:orbit/test/BaseServer:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_B1_0 == 'e') \
&& (TC_IMPL_TC_test_B1_1 == 'v') \
&& (TC_IMPL_TC_test_B1_2 == 'e') \
&& (TC_IMPL_TC_test_B1_3 == 'r') \
&& (TC_IMPL_TC_test_B1_4 == 'y') \
&& (TC_IMPL_TC_test_B1_5 == 't') \
&& (TC_IMPL_TC_test_B1_6 == 'h') \
&& (TC_IMPL_TC_test_B1_7 == 'i') \
&& (TC_IMPL_TC_test_B1_8 == 'n') \
&& (TC_IMPL_TC_test_B1_9 == 'g') \
) && !defined(TC_DEF_TC_test_B1)
#define TC_DEF_TC_test_B1 1
const struct CORBA_TypeCode_struct TC_test_B1_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "B1", "IDL:orbit/test/B1:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_B2_0 == 'e') \
&& (TC_IMPL_TC_test_B2_1 == 'v') \
&& (TC_IMPL_TC_test_B2_2 == 'e') \
&& (TC_IMPL_TC_test_B2_3 == 'r') \
&& (TC_IMPL_TC_test_B2_4 == 'y') \
&& (TC_IMPL_TC_test_B2_5 == 't') \
&& (TC_IMPL_TC_test_B2_6 == 'h') \
&& (TC_IMPL_TC_test_B2_7 == 'i') \
&& (TC_IMPL_TC_test_B2_8 == 'n') \
&& (TC_IMPL_TC_test_B2_9 == 'g') \
) && !defined(TC_DEF_TC_test_B2)
#define TC_DEF_TC_test_B2 1
const struct CORBA_TypeCode_struct TC_test_B2_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "B2", "IDL:orbit/test/B2:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_C1_0 == 'e') \
&& (TC_IMPL_TC_test_C1_1 == 'v') \
&& (TC_IMPL_TC_test_C1_2 == 'e') \
&& (TC_IMPL_TC_test_C1_3 == 'r') \
&& (TC_IMPL_TC_test_C1_4 == 'y') \
&& (TC_IMPL_TC_test_C1_5 == 't') \
&& (TC_IMPL_TC_test_C1_6 == 'h') \
&& (TC_IMPL_TC_test_C1_7 == 'i') \
&& (TC_IMPL_TC_test_C1_8 == 'n') \
&& (TC_IMPL_TC_test_C1_9 == 'g') \
) && !defined(TC_DEF_TC_test_C1)
#define TC_DEF_TC_test_C1 1
const struct CORBA_TypeCode_struct TC_test_C1_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "C1", "IDL:orbit/test/C1:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_DerivedServer_0 == 'e') \
&& (TC_IMPL_TC_test_DerivedServer_1 == 'v') \
&& (TC_IMPL_TC_test_DerivedServer_2 == 'e') \
&& (TC_IMPL_TC_test_DerivedServer_3 == 'r') \
&& (TC_IMPL_TC_test_DerivedServer_4 == 'y') \
&& (TC_IMPL_TC_test_DerivedServer_5 == 't') \
&& (TC_IMPL_TC_test_DerivedServer_6 == 'h') \
&& (TC_IMPL_TC_test_DerivedServer_7 == 'i') \
&& (TC_IMPL_TC_test_DerivedServer_8 == 'n') \
&& (TC_IMPL_TC_test_DerivedServer_9 == 'g') \
) && !defined(TC_DEF_TC_test_DerivedServer)
#define TC_DEF_TC_test_DerivedServer 1
const struct CORBA_TypeCode_struct TC_test_DerivedServer_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "DerivedServer", "IDL:orbit/test/DerivedServer:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_FixedLengthUnion_0 == 'e') \
&& (TC_IMPL_TC_test_FixedLengthUnion_1 == 'v') \
&& (TC_IMPL_TC_test_FixedLengthUnion_2 == 'e') \
&& (TC_IMPL_TC_test_FixedLengthUnion_3 == 'r') \
&& (TC_IMPL_TC_test_FixedLengthUnion_4 == 'y') \
&& (TC_IMPL_TC_test_FixedLengthUnion_5 == 't') \
&& (TC_IMPL_TC_test_FixedLengthUnion_6 == 'h') \
&& (TC_IMPL_TC_test_FixedLengthUnion_7 == 'i') \
&& (TC_IMPL_TC_test_FixedLengthUnion_8 == 'n') \
&& (TC_IMPL_TC_test_FixedLengthUnion_9 == 'g') \
) && !defined(TC_DEF_TC_test_FixedLengthUnion)
#define TC_DEF_TC_test_FixedLengthUnion 1
static const CORBA_char anon_sublabel_values_array244[] =
   { 'a', 'b', 'c', 'd', 'e' };
static const char *anon_subnames_array241[] = { "x", "y", "z", "v" };
static const CORBA_TypeCode anon_subtypes_array242[] =
   { (CORBA_TypeCode) & TC_CORBA_long_struct,
(CORBA_TypeCode) & TC_CORBA_char_struct, (CORBA_TypeCode) & TC_CORBA_boolean_struct,
(CORBA_TypeCode) & TC_CORBA_boolean_struct, (CORBA_TypeCode) & TC_test_FixedLengthStruct_struct };
static const CORBA_any anon_sublabels_array243[] =
   { {(CORBA_TypeCode) & TC_CORBA_char_struct,
      (gpointer) & anon_sublabel_values_array244[0], CORBA_FALSE},
   {(CORBA_TypeCode) & TC_CORBA_char_struct,
    (gpointer) & anon_sublabel_values_array244[1], CORBA_FALSE},
   {(CORBA_TypeCode) & TC_CORBA_char_struct,
    (gpointer) & anon_sublabel_values_array244[2], CORBA_FALSE},
   {(CORBA_TypeCode) & TC_CORBA_char_struct,
    (gpointer) & anon_sublabel_values_array244[3], CORBA_FALSE},
   {(CORBA_TypeCode) & TC_CORBA_char_struct,
    (gpointer) & anon_sublabel_values_array244[4], CORBA_FALSE} };
const struct CORBA_TypeCode_struct TC_test_FixedLengthUnion_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_union, "FixedLengthUnion", "IDL:orbit/test/FixedLengthUnion:1.0",
   0, 5,
   (const char **) anon_subnames_array241,
   (CORBA_TypeCode *) anon_subtypes_array242,
   (CORBA_any *) anon_sublabels_array243,
   (CORBA_TypeCode) & TC_CORBA_char_struct, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_VariableLengthUnion_0 == 'e') \
&& (TC_IMPL_TC_test_VariableLengthUnion_1 == 'v') \
&& (TC_IMPL_TC_test_VariableLengthUnion_2 == 'e') \
&& (TC_IMPL_TC_test_VariableLengthUnion_3 == 'r') \
&& (TC_IMPL_TC_test_VariableLengthUnion_4 == 'y') \
&& (TC_IMPL_TC_test_VariableLengthUnion_5 == 't') \
&& (TC_IMPL_TC_test_VariableLengthUnion_6 == 'h') \
&& (TC_IMPL_TC_test_VariableLengthUnion_7 == 'i') \
&& (TC_IMPL_TC_test_VariableLengthUnion_8 == 'n') \
&& (TC_IMPL_TC_test_VariableLengthUnion_9 == 'g') \
) && !defined(TC_DEF_TC_test_VariableLengthUnion)
#define TC_DEF_TC_test_VariableLengthUnion 1
static const CORBA_long anon_sublabel_values_array249[] =
   { 1, 2, 3, 4, 5, 6, 7, 8 };
static const char *anon_subnames_array246[] =
   { "x", "w", "y", "z", "a", "b", "c", "d" };
static const CORBA_TypeCode anon_subtypes_array247[] =
   { (CORBA_TypeCode) & TC_CORBA_long_struct,
(CORBA_TypeCode) & TC_CORBA_long_struct, (CORBA_TypeCode) & TC_CORBA_string_struct,
(CORBA_TypeCode) & TC_CORBA_boolean_struct, (CORBA_TypeCode) & TC_CORBA_boolean_struct,
(CORBA_TypeCode) & TC_test_VariableLengthStruct_struct, (CORBA_TypeCode) & TC_test_StrSeq_struct,
(CORBA_TypeCode) & TC_test_FixedLengthUnion_struct, (CORBA_TypeCode) & TC_test_StrArray_struct };
static const CORBA_any anon_sublabels_array248[] =
   { {(CORBA_TypeCode) & TC_CORBA_long_struct,
      (gpointer) & anon_sublabel_values_array249[0], CORBA_FALSE},
   {(CORBA_TypeCode) & TC_CORBA_octet_struct, (int *) &ORBit_zero_int,
    CORBA_FALSE}, {(CORBA_TypeCode) & TC_CORBA_long_struct,
		   (gpointer) & anon_sublabel_values_array249[1],
		   CORBA_FALSE}, {(CORBA_TypeCode) & TC_CORBA_long_struct,
				  (gpointer) &
				  anon_sublabel_values_array249[2],
				  CORBA_FALSE},
   {(CORBA_TypeCode) & TC_CORBA_long_struct,
    (gpointer) & anon_sublabel_values_array249[3], CORBA_FALSE},
   {(CORBA_TypeCode) & TC_CORBA_long_struct,
    (gpointer) & anon_sublabel_values_array249[4], CORBA_FALSE},
   {(CORBA_TypeCode) & TC_CORBA_long_struct,
    (gpointer) & anon_sublabel_values_array249[5], CORBA_FALSE},
   {(CORBA_TypeCode) & TC_CORBA_long_struct,
    (gpointer) & anon_sublabel_values_array249[6], CORBA_FALSE},
   {(CORBA_TypeCode) & TC_CORBA_long_struct,
    (gpointer) & anon_sublabel_values_array249[7], CORBA_FALSE} };
const struct CORBA_TypeCode_struct TC_test_VariableLengthUnion_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_union, "VariableLengthUnion",
      "IDL:orbit/test/VariableLengthUnion:1.0",
   0, 9,
   (const char **) anon_subnames_array246,
   (CORBA_TypeCode *) anon_subtypes_array247,
   (CORBA_any *) anon_sublabels_array248,
   (CORBA_TypeCode) & TC_CORBA_long_struct, 0, 1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_EnumUnion_0 == 'e') \
&& (TC_IMPL_TC_test_EnumUnion_1 == 'v') \
&& (TC_IMPL_TC_test_EnumUnion_2 == 'e') \
&& (TC_IMPL_TC_test_EnumUnion_3 == 'r') \
&& (TC_IMPL_TC_test_EnumUnion_4 == 'y') \
&& (TC_IMPL_TC_test_EnumUnion_5 == 't') \
&& (TC_IMPL_TC_test_EnumUnion_6 == 'h') \
&& (TC_IMPL_TC_test_EnumUnion_7 == 'i') \
&& (TC_IMPL_TC_test_EnumUnion_8 == 'n') \
&& (TC_IMPL_TC_test_EnumUnion_9 == 'g') \
) && !defined(TC_DEF_TC_test_EnumUnion)
#define TC_DEF_TC_test_EnumUnion 1
static const test_Colour anon_sublabel_values_array254[] =
   { test_red, test_blue };
static const char *anon_subnames_array251[] = { "x", "y" };
static const CORBA_TypeCode anon_subtypes_array252[] =
   { (CORBA_TypeCode) & TC_CORBA_long_struct,
(CORBA_TypeCode) & TC_CORBA_boolean_struct };
static const CORBA_any anon_sublabels_array253[] =
   { {(CORBA_TypeCode) & TC_test_Colour_struct,
      (gpointer) & anon_sublabel_values_array254[0], CORBA_FALSE},
   {(CORBA_TypeCode) & TC_test_Colour_struct,
    (gpointer) & anon_sublabel_values_array254[1], CORBA_FALSE} };
const struct CORBA_TypeCode_struct TC_test_EnumUnion_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_union, "EnumUnion", "IDL:orbit/test/EnumUnion:1.0",
   0, 2,
   (const char **) anon_subnames_array251,
   (CORBA_TypeCode *) anon_subtypes_array252,
   (CORBA_any *) anon_sublabels_array253,
   (CORBA_TypeCode) & TC_test_Colour_struct, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_BooleanUnion_0 == 'e') \
&& (TC_IMPL_TC_test_BooleanUnion_1 == 'v') \
&& (TC_IMPL_TC_test_BooleanUnion_2 == 'e') \
&& (TC_IMPL_TC_test_BooleanUnion_3 == 'r') \
&& (TC_IMPL_TC_test_BooleanUnion_4 == 'y') \
&& (TC_IMPL_TC_test_BooleanUnion_5 == 't') \
&& (TC_IMPL_TC_test_BooleanUnion_6 == 'h') \
&& (TC_IMPL_TC_test_BooleanUnion_7 == 'i') \
&& (TC_IMPL_TC_test_BooleanUnion_8 == 'n') \
&& (TC_IMPL_TC_test_BooleanUnion_9 == 'g') \
) && !defined(TC_DEF_TC_test_BooleanUnion)
#define TC_DEF_TC_test_BooleanUnion 1
static const CORBA_boolean anon_sublabel_values_array259[] = { 0, 1 };
static const char *anon_subnames_array256[] = { "x", "y" };
static const CORBA_TypeCode anon_subtypes_array257[] =
   { (CORBA_TypeCode) & TC_test_VariableLengthStruct_struct,
(CORBA_TypeCode) & TC_CORBA_string_struct };
static const CORBA_any anon_sublabels_array258[] =
   { {(CORBA_TypeCode) & TC_CORBA_boolean_struct,
      (gpointer) & anon_sublabel_values_array259[0], CORBA_FALSE},
   {(CORBA_TypeCode) & TC_CORBA_boolean_struct,
    (gpointer) & anon_sublabel_values_array259[1], CORBA_FALSE} };
const struct CORBA_TypeCode_struct TC_test_BooleanUnion_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_union, "BooleanUnion", "IDL:orbit/test/BooleanUnion:1.0",
   0, 2,
   (const char **) anon_subnames_array256,
   (CORBA_TypeCode *) anon_subtypes_array257,
   (CORBA_any *) anon_sublabels_array258,
   (CORBA_TypeCode) & TC_CORBA_boolean_struct, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_StrArray2_0 == 'e') \
&& (TC_IMPL_TC_test_StrArray2_1 == 'v') \
&& (TC_IMPL_TC_test_StrArray2_2 == 'e') \
&& (TC_IMPL_TC_test_StrArray2_3 == 'r') \
&& (TC_IMPL_TC_test_StrArray2_4 == 'y') \
&& (TC_IMPL_TC_test_StrArray2_5 == 't') \
&& (TC_IMPL_TC_test_StrArray2_6 == 'h') \
&& (TC_IMPL_TC_test_StrArray2_7 == 'i') \
&& (TC_IMPL_TC_test_StrArray2_8 == 'n') \
&& (TC_IMPL_TC_test_StrArray2_9 == 'g') \
) && !defined(TC_DEF_TC_test_StrArray2)
#define TC_DEF_TC_test_StrArray2 1
static const CORBA_TypeCode anon_subtypes_array272[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
static const struct CORBA_TypeCode_struct anonTC_269_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_array, NULL, NULL,
   20, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array272,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
static const CORBA_TypeCode anon_subtypes_array267[] =
   { (CORBA_TypeCode) & anonTC_269_struct };
const struct CORBA_TypeCode_struct TC_test_StrArray2_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "StrArray2", "IDL:orbit/test/StrArray2:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array267,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_ArrayUnion_0 == 'e') \
&& (TC_IMPL_TC_test_ArrayUnion_1 == 'v') \
&& (TC_IMPL_TC_test_ArrayUnion_2 == 'e') \
&& (TC_IMPL_TC_test_ArrayUnion_3 == 'r') \
&& (TC_IMPL_TC_test_ArrayUnion_4 == 'y') \
&& (TC_IMPL_TC_test_ArrayUnion_5 == 't') \
&& (TC_IMPL_TC_test_ArrayUnion_6 == 'h') \
&& (TC_IMPL_TC_test_ArrayUnion_7 == 'i') \
&& (TC_IMPL_TC_test_ArrayUnion_8 == 'n') \
&& (TC_IMPL_TC_test_ArrayUnion_9 == 'g') \
) && !defined(TC_DEF_TC_test_ArrayUnion)
#define TC_DEF_TC_test_ArrayUnion 1
static const CORBA_boolean anon_sublabel_values_array278[] = { 0 };
static const char *anon_subnames_array275[] = { "d" };
static const CORBA_TypeCode anon_subtypes_array276[] =
   { (CORBA_TypeCode) & TC_test_StrArray2_struct };
static const CORBA_any anon_sublabels_array277[] =
   { {(CORBA_TypeCode) & TC_CORBA_boolean_struct,
      (gpointer) & anon_sublabel_values_array278[0], CORBA_FALSE} };
const struct CORBA_TypeCode_struct TC_test_ArrayUnion_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_union, "ArrayUnion", "IDL:orbit/test/ArrayUnion:1.0",
   0, 1,
   (const char **) anon_subnames_array275,
   (CORBA_TypeCode *) anon_subtypes_array276,
   (CORBA_any *) anon_sublabels_array277,
   (CORBA_TypeCode) & TC_CORBA_boolean_struct, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_UnionServer_0 == 'e') \
&& (TC_IMPL_TC_test_UnionServer_1 == 'v') \
&& (TC_IMPL_TC_test_UnionServer_2 == 'e') \
&& (TC_IMPL_TC_test_UnionServer_3 == 'r') \
&& (TC_IMPL_TC_test_UnionServer_4 == 'y') \
&& (TC_IMPL_TC_test_UnionServer_5 == 't') \
&& (TC_IMPL_TC_test_UnionServer_6 == 'h') \
&& (TC_IMPL_TC_test_UnionServer_7 == 'i') \
&& (TC_IMPL_TC_test_UnionServer_8 == 'n') \
&& (TC_IMPL_TC_test_UnionServer_9 == 'g') \
) && !defined(TC_DEF_TC_test_UnionServer)
#define TC_DEF_TC_test_UnionServer 1
const struct CORBA_TypeCode_struct TC_test_UnionServer_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "UnionServer", "IDL:orbit/test/UnionServer:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_test_AnyServer_0 == 'e') \
&& (TC_IMPL_TC_test_AnyServer_1 == 'v') \
&& (TC_IMPL_TC_test_AnyServer_2 == 'e') \
&& (TC_IMPL_TC_test_AnyServer_3 == 'r') \
&& (TC_IMPL_TC_test_AnyServer_4 == 'y') \
&& (TC_IMPL_TC_test_AnyServer_5 == 't') \
&& (TC_IMPL_TC_test_AnyServer_6 == 'h') \
&& (TC_IMPL_TC_test_AnyServer_7 == 'i') \
&& (TC_IMPL_TC_test_AnyServer_8 == 'n') \
&& (TC_IMPL_TC_test_AnyServer_9 == 'g') \
) && !defined(TC_DEF_TC_test_AnyServer)
#define TC_DEF_TC_test_AnyServer 1
const struct CORBA_TypeCode_struct TC_test_AnyServer_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "AnyServer", "IDL:orbit/test/AnyServer:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long test_TestFactory__classid = 0;
CORBA_unsigned_long test_TransientObj__classid = 0;
gpointer
test_FixedLengthStruct__free(gpointer mem, gpointer dat,
			     CORBA_boolean free_strings)
{
   test_FixedLengthStruct *var = mem;

   return (gpointer) (var + 1);
}

test_FixedLengthStruct *
test_FixedLengthStruct__alloc(void)
{
   test_FixedLengthStruct *retval;

   retval =
      ORBit_alloc(sizeof(test_FixedLengthStruct),
		  (ORBit_free_childvals) test_FixedLengthStruct__free,
		  GUINT_TO_POINTER(1));
   return retval;
}

gpointer
test_VariableLengthStruct__free(gpointer mem, gpointer dat,
				CORBA_boolean free_strings)
{
   test_VariableLengthStruct *var = mem;

   if (free_strings) {
      CORBA_string__free(&(var->a), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

test_VariableLengthStruct *
test_VariableLengthStruct__alloc(void)
{
   test_VariableLengthStruct *retval;

   retval =
      ORBit_alloc(sizeof(test_VariableLengthStruct),
		  (ORBit_free_childvals) test_VariableLengthStruct__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->a), '\0', sizeof(retval->a));
   return retval;
}

gpointer
test_CompoundStruct__free(gpointer mem, gpointer dat,
			  CORBA_boolean free_strings)
{
   test_CompoundStruct *var = mem;

   {
      test_VariableLengthStruct__free(&(var->a), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

test_CompoundStruct *
test_CompoundStruct__alloc(void)
{
   test_CompoundStruct *retval;

   retval =
      ORBit_alloc(sizeof(test_CompoundStruct),
		  (ORBit_free_childvals) test_CompoundStruct__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->a), '\0', sizeof(retval->a));
   return retval;
}

CORBA_unsigned_long test_StructServer__classid = 0;

#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_string_0 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_1 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_2 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_3 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_4 == 'y') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_5 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_6 == 'h') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_7 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_8 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_9 == 'g') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_string)
#define ORBIT_DEF_CORBA_sequence_CORBA_string 1

gpointer
CORBA_sequence_CORBA_string__free(gpointer mem, gpointer dat,
				  CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_string *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CORBA_string *
CORBA_sequence_CORBA_string__alloc(void)
{
   CORBA_sequence_CORBA_string *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_string),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_string__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CORBA_char **
CORBA_sequence_CORBA_string_allocbuf(CORBA_unsigned_long len)
{
   CORBA_char **retval =
      ORBit_alloc(sizeof(CORBA_char *) * len,
		  (ORBit_free_childvals) CORBA_string__free,
		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(CORBA_char *) * len);
   return retval;
}
#endif

gpointer
test_StrSeq__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   return CORBA_sequence_CORBA_string__free(mem, dat, free_strings);
}

test_StrSeq *
test_StrSeq__alloc(void)
{
   return CORBA_sequence_CORBA_string__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_test_CompoundStruct_0 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_test_CompoundStruct_1 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_test_CompoundStruct_2 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_test_CompoundStruct_3 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_test_CompoundStruct_4 == 'y') \
&& (ORBIT_IMPL_CORBA_sequence_test_CompoundStruct_5 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_test_CompoundStruct_6 == 'h') \
&& (ORBIT_IMPL_CORBA_sequence_test_CompoundStruct_7 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_test_CompoundStruct_8 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_test_CompoundStruct_9 == 'g') \
) && !defined(ORBIT_DEF_CORBA_sequence_test_CompoundStruct)
#define ORBIT_DEF_CORBA_sequence_test_CompoundStruct 1

gpointer
CORBA_sequence_test_CompoundStruct__free(gpointer mem, gpointer dat,
					 CORBA_boolean free_strings)
{
   CORBA_sequence_test_CompoundStruct *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_test_CompoundStruct *
CORBA_sequence_test_CompoundStruct__alloc(void)
{
   CORBA_sequence_test_CompoundStruct *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_test_CompoundStruct),
		  (ORBit_free_childvals)
		  CORBA_sequence_test_CompoundStruct__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 2;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

test_CompoundStruct *
CORBA_sequence_test_CompoundStruct_allocbuf(CORBA_unsigned_long len)
{
   test_CompoundStruct *retval =
      ORBit_alloc(sizeof(test_CompoundStruct) * len,
		  (ORBit_free_childvals) test_CompoundStruct__free,
		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(test_CompoundStruct) * len);
   return retval;
}
#endif

gpointer
test_BoundedStructSeq__free(gpointer mem, gpointer dat,
			    CORBA_boolean free_strings)
{
   return CORBA_sequence_test_CompoundStruct__free(mem, dat, free_strings);
}

test_BoundedStructSeq *
test_BoundedStructSeq__alloc(void)
{
   return CORBA_sequence_test_CompoundStruct__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_long_0 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_1 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_2 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_3 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_4 == 'y') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_5 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_6 == 'h') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_7 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_8 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_9 == 'g') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_long)
#define ORBIT_DEF_CORBA_sequence_CORBA_long 1

gpointer
CORBA_sequence_CORBA_long__free(gpointer mem, gpointer dat,
				CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_long *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CORBA_long *
CORBA_sequence_CORBA_long__alloc(void)
{
   CORBA_sequence_CORBA_long *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_long),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_long__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 2;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CORBA_long *
CORBA_sequence_CORBA_long_allocbuf(CORBA_unsigned_long len)
{
   CORBA_long *retval =
      ORBit_alloc(sizeof(CORBA_long) * len, (ORBit_free_childvals) NULL,
		  GUINT_TO_POINTER(len));
   return retval;
}
#endif

gpointer
test_BoundedLongSeq__free(gpointer mem, gpointer dat,
			  CORBA_boolean free_strings)
{
   return CORBA_sequence_CORBA_long__free(mem, dat, free_strings);
}

test_BoundedLongSeq *
test_BoundedLongSeq__alloc(void)
{
   return CORBA_sequence_CORBA_long__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_long_0 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_1 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_2 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_3 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_4 == 'y') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_5 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_6 == 'h') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_7 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_8 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_9 == 'g') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_long)
#define ORBIT_DEF_CORBA_sequence_CORBA_long 1

gpointer
CORBA_sequence_CORBA_long__free(gpointer mem, gpointer dat,
				CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_long *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CORBA_long *
CORBA_sequence_CORBA_long__alloc(void)
{
   CORBA_sequence_CORBA_long *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_long),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_long__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CORBA_long *
CORBA_sequence_CORBA_long_allocbuf(CORBA_unsigned_long len)
{
   CORBA_long *retval =
      ORBit_alloc(sizeof(CORBA_long) * len, (ORBit_free_childvals) NULL,
		  GUINT_TO_POINTER(len));
   return retval;
}
#endif

gpointer
test_LongSeq__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   return CORBA_sequence_CORBA_long__free(mem, dat, free_strings);
}

test_LongSeq *
test_LongSeq__alloc(void)
{
   return CORBA_sequence_CORBA_long__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_test_StrSeq_0 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_1 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_2 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_3 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_4 == 'y') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_5 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_6 == 'h') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_7 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_8 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_9 == 'g') \
) && !defined(ORBIT_DEF_CORBA_sequence_test_StrSeq)
#define ORBIT_DEF_CORBA_sequence_test_StrSeq 1

gpointer
CORBA_sequence_test_StrSeq__free(gpointer mem, gpointer dat,
				 CORBA_boolean free_strings)
{
   CORBA_sequence_test_StrSeq *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_test_StrSeq *
CORBA_sequence_test_StrSeq__alloc(void)
{
   CORBA_sequence_test_StrSeq *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_test_StrSeq),
		  (ORBit_free_childvals) CORBA_sequence_test_StrSeq__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

test_StrSeq *
CORBA_sequence_test_StrSeq_allocbuf(CORBA_unsigned_long len)
{
   test_StrSeq *retval =
      ORBit_alloc(sizeof(test_StrSeq) * len,
		  (ORBit_free_childvals) test_StrSeq__free,
		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(test_StrSeq) * len);
   return retval;
}
#endif

gpointer
test_StrSeqSeq__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   return CORBA_sequence_test_StrSeq__free(mem, dat, free_strings);
}

test_StrSeqSeq *
test_StrSeqSeq__alloc(void)
{
   return CORBA_sequence_test_StrSeq__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_any_0 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_any_1 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_any_2 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_any_3 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_any_4 == 'y') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_any_5 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_any_6 == 'h') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_any_7 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_any_8 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_any_9 == 'g') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_any)
#define ORBIT_DEF_CORBA_sequence_CORBA_any 1

gpointer
CORBA_sequence_CORBA_any__free(gpointer mem, gpointer dat,
			       CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_any *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CORBA_any *
CORBA_sequence_CORBA_any__alloc(void)
{
   CORBA_sequence_CORBA_any *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_any),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_any__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CORBA_any *
CORBA_sequence_CORBA_any_allocbuf(CORBA_unsigned_long len)
{
   CORBA_any *retval =
      ORBit_alloc(sizeof(CORBA_any) * len,
		  (ORBit_free_childvals) CORBA_any__free,
		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(CORBA_any) * len);
   return retval;
}
#endif

gpointer
test_AnySeq__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   return CORBA_sequence_CORBA_any__free(mem, dat, free_strings);
}

test_AnySeq *
test_AnySeq__alloc(void)
{
   return CORBA_sequence_CORBA_any__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_test_StrSeq_0 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_1 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_2 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_3 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_4 == 'y') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_5 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_6 == 'h') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_7 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_8 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_test_StrSeq_9 == 'g') \
) && !defined(ORBIT_DEF_CORBA_sequence_test_StrSeq)
#define ORBIT_DEF_CORBA_sequence_test_StrSeq 1

gpointer
CORBA_sequence_test_StrSeq__free(gpointer mem, gpointer dat,
				 CORBA_boolean free_strings)
{
   CORBA_sequence_test_StrSeq *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_test_StrSeq *
CORBA_sequence_test_StrSeq__alloc(void)
{
   CORBA_sequence_test_StrSeq *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_test_StrSeq),
		  (ORBit_free_childvals) CORBA_sequence_test_StrSeq__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

test_StrSeq *
CORBA_sequence_test_StrSeq_allocbuf(CORBA_unsigned_long len)
{
   test_StrSeq *retval =
      ORBit_alloc(sizeof(test_StrSeq) * len,
		  (ORBit_free_childvals) test_StrSeq__free,
		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(test_StrSeq) * len);
   return retval;
}
#endif

gpointer
test_StructWithSequenceInIt__free(gpointer mem, gpointer dat,
				  CORBA_boolean free_strings)
{
   test_StructWithSequenceInIt *var = mem;

   {
      test_StrSeqSeq__free(&(var->theSeq), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

test_StructWithSequenceInIt *
test_StructWithSequenceInIt__alloc(void)
{
   test_StructWithSequenceInIt *retval;

   retval =
      ORBit_alloc(sizeof(test_StructWithSequenceInIt),
		  (ORBit_free_childvals) test_StructWithSequenceInIt__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->theSeq), '\0', sizeof(retval->theSeq));
   return retval;
}

CORBA_unsigned_long test_SequenceServer__classid = 0;

#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_long_0 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_1 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_2 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_3 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_4 == 'y') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_5 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_6 == 'h') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_7 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_8 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_9 == 'g') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_long)
#define ORBIT_DEF_CORBA_sequence_CORBA_long 1

gpointer
CORBA_sequence_CORBA_long__free(gpointer mem, gpointer dat,
				CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_long *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CORBA_long *
CORBA_sequence_CORBA_long__alloc(void)
{
   CORBA_sequence_CORBA_long *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_long),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_long__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CORBA_long *
CORBA_sequence_CORBA_long_allocbuf(CORBA_unsigned_long len)
{
   CORBA_long *retval =
      ORBit_alloc(sizeof(CORBA_long) * len, (ORBit_free_childvals) NULL,
		  GUINT_TO_POINTER(len));
   return retval;
}
#endif

gpointer
test_TestException__free(gpointer mem, gpointer dat,
			 CORBA_boolean free_strings)
{
   test_TestException *var = mem;

   if (free_strings) {
      CORBA_string__free(&(var->reason), NULL, free_strings);
   }
   {
      test_LongSeq__free(&(var->aseq), NULL, free_strings);
   }
   {
      test_TestFactory__free(&(var->factory), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

test_TestException *
test_TestException__alloc(void)
{
   test_TestException *retval;

   retval =
      ORBit_alloc(sizeof(test_TestException),
		  (ORBit_free_childvals) test_TestException__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->reason), '\0', sizeof(retval->reason));
   memset(&(retval->aseq), '\0', sizeof(retval->aseq));
   memset(&(retval->factory), '\0', sizeof(retval->factory));
   return retval;
}

gpointer
test_LongArray__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   gpointer retval = ((guchar *) mem) + sizeof(test_LongArray);

   return retval;
}

test_LongArray_slice *
test_LongArray__alloc(void)
{
   test_LongArray_slice *retval;

   retval =
      ORBit_alloc(sizeof(test_LongArray), (ORBit_free_childvals) NULL, NULL);
   return retval;
}

gpointer
test_StrArray__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   int n0;
   gpointer retval = ((guchar *) mem) + sizeof(test_StrArray);

   for (n0 = 0; n0 < 2; n0++) {
      CORBA_string__free(&((test_StrArray_slice *) mem)[n0], NULL,
			 free_strings);
   }
   return retval;
}

test_StrArray_slice *
test_StrArray__alloc(void)
{
   test_StrArray_slice *retval;

   retval =
      ORBit_alloc(sizeof(test_StrArray),
		  (ORBit_free_childvals) test_StrArray__free,
		  GUINT_TO_POINTER(1));
   memset(retval, '\0', sizeof(test_StrArray));
   return retval;
}

gpointer
test_StrArrayMultiDimensional__free(gpointer mem, gpointer dat,
				    CORBA_boolean free_strings)
{
   int n0;
   int n1;
   int n2;
   gpointer retval = ((guchar *) mem) + sizeof(test_StrArrayMultiDimensional);

   for (n0 = 0; n0 < 2; n0++) {
      for (n1 = 0; n1 < 3; n1++) {
	 for (n2 = 0; n2 < 5; n2++) {
	    CORBA_string__free(&((test_StrArrayMultiDimensional_slice *) mem)
			       [n0][n1][n2], NULL, free_strings);
	 }
      }
   }
   return retval;
}

test_StrArrayMultiDimensional_slice *
test_StrArrayMultiDimensional__alloc(void)
{
   test_StrArrayMultiDimensional_slice *retval;

   retval =
      ORBit_alloc(sizeof(test_StrArrayMultiDimensional),
		  (ORBit_free_childvals) test_StrArrayMultiDimensional__free,
		  GUINT_TO_POINTER(1));
   memset(retval, '\0', sizeof(test_StrArrayMultiDimensional));
   return retval;
}

gpointer
test_VariableLengthStructArray__free(gpointer mem, gpointer dat,
				     CORBA_boolean free_strings)
{
   int n0;
   gpointer retval =
      ((guchar *) mem) + sizeof(test_VariableLengthStructArray);
   for (n0 = 0; n0 < 2; n0++) {
      test_VariableLengthStruct__free(&
				      ((test_VariableLengthStructArray_slice
					*) mem)[n0], NULL, free_strings);
   }
   return retval;
}

test_VariableLengthStructArray_slice *
test_VariableLengthStructArray__alloc(void)
{
   test_VariableLengthStructArray_slice *retval;

   retval =
      ORBit_alloc(sizeof(test_VariableLengthStructArray),
		  (ORBit_free_childvals) test_VariableLengthStructArray__free,
		  GUINT_TO_POINTER(1));
   memset(retval, '\0', sizeof(test_VariableLengthStructArray));
   return retval;
}

CORBA_unsigned_long test_ArrayServer__classid = 0;
CORBA_unsigned_long test_BasicServer__classid = 0;
CORBA_unsigned_long test_BaseServer__classid = 0;
CORBA_unsigned_long test_B1__classid = 0;
CORBA_unsigned_long test_B2__classid = 0;
CORBA_unsigned_long test_C1__classid = 0;
CORBA_unsigned_long test_DerivedServer__classid = 0;
gpointer
test_FixedLengthUnion__free(gpointer mem, gpointer dat,
			    CORBA_boolean free_strings)
{
   test_FixedLengthUnion *val = mem;

   switch (val->_d) {
     case 'a':
	break;
     case 'b':
	break;
     case 'c':
     case 'd':
	break;
     case 'e':
	break;
     default:
	break;
   }
   return (gpointer) (val + 1);
}

test_FixedLengthUnion *
test_FixedLengthUnion__alloc(void)
{
   test_FixedLengthUnion *retval;

   retval =
      ORBit_alloc(sizeof(test_FixedLengthUnion),
		  (ORBit_free_childvals) test_FixedLengthUnion__free,
		  GUINT_TO_POINTER(1));
   return retval;
}

#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_string_0 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_1 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_2 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_3 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_4 == 'y') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_5 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_6 == 'h') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_7 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_8 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_9 == 'g') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_string)
#define ORBIT_DEF_CORBA_sequence_CORBA_string 1

gpointer
CORBA_sequence_CORBA_string__free(gpointer mem, gpointer dat,
				  CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_string *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CORBA_string *
CORBA_sequence_CORBA_string__alloc(void)
{
   CORBA_sequence_CORBA_string *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_string),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_string__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CORBA_char **
CORBA_sequence_CORBA_string_allocbuf(CORBA_unsigned_long len)
{
   CORBA_char **retval =
      ORBit_alloc(sizeof(CORBA_char *) * len,
		  (ORBit_free_childvals) CORBA_string__free,
		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(CORBA_char *) * len);
   return retval;
}
#endif

gpointer
test_VariableLengthUnion__free(gpointer mem, gpointer dat,
			       CORBA_boolean free_strings)
{
   test_VariableLengthUnion *val = mem;

   switch (val->_d) {
     case 1:
	break;
     default:
	break;
     case 2:
	CORBA_string__free(&(val->_u.y), NULL, free_strings);
	break;
     case 3:
     case 4:
	break;
     case 5:
	test_VariableLengthStruct__free(&(val->_u.a), NULL, free_strings);
	break;
     case 6:
	test_StrSeq__free(&(val->_u.b), NULL, free_strings);
	break;
     case 7:
	break;
     case 8:
	test_StrArray__free(&(val->_u.d), NULL, free_strings);
	break;
   }
   return (gpointer) (val + 1);
}

test_VariableLengthUnion *
test_VariableLengthUnion__alloc(void)
{
   test_VariableLengthUnion *retval;

   retval =
      ORBit_alloc(sizeof(test_VariableLengthUnion),
		  (ORBit_free_childvals) test_VariableLengthUnion__free,
		  GUINT_TO_POINTER(1));
   memset(retval, '\0', sizeof(test_VariableLengthUnion));
   return retval;
}

gpointer
test_EnumUnion__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   test_EnumUnion *val = mem;

   switch (val->_d) {
     case test_red:
	break;
     case test_blue:
	break;
     default:
	break;
   }
   return (gpointer) (val + 1);
}

test_EnumUnion *
test_EnumUnion__alloc(void)
{
   test_EnumUnion *retval;

   retval =
      ORBit_alloc(sizeof(test_EnumUnion),
		  (ORBit_free_childvals) test_EnumUnion__free,
		  GUINT_TO_POINTER(1));
   return retval;
}

gpointer
test_BooleanUnion__free(gpointer mem, gpointer dat,
			CORBA_boolean free_strings)
{
   test_BooleanUnion *val = mem;

   switch (val->_d) {
     case 0:
	test_VariableLengthStruct__free(&(val->_u.x), NULL, free_strings);
	break;
     case 1:
	CORBA_string__free(&(val->_u.y), NULL, free_strings);
	break;
     default:
	break;
   }
   return (gpointer) (val + 1);
}

test_BooleanUnion *
test_BooleanUnion__alloc(void)
{
   test_BooleanUnion *retval;

   retval =
      ORBit_alloc(sizeof(test_BooleanUnion),
		  (ORBit_free_childvals) test_BooleanUnion__free,
		  GUINT_TO_POINTER(1));
   memset(retval, '\0', sizeof(test_BooleanUnion));
   return retval;
}

gpointer
test_StrArray2__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   int n0;
   gpointer retval = ((guchar *) mem) + sizeof(test_StrArray2);

   for (n0 = 0; n0 < 20; n0++) {
      CORBA_string__free(&((test_StrArray2_slice *) mem)[n0], NULL,
			 free_strings);
   }
   return retval;
}

test_StrArray2_slice *
test_StrArray2__alloc(void)
{
   test_StrArray2_slice *retval;

   retval =
      ORBit_alloc(sizeof(test_StrArray2),
		  (ORBit_free_childvals) test_StrArray2__free,
		  GUINT_TO_POINTER(1));
   memset(retval, '\0', sizeof(test_StrArray2));
   return retval;
}

gpointer
test_ArrayUnion__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   test_ArrayUnion *val = mem;

   switch (val->_d) {
     case 0:
	test_StrArray2__free(&(val->_u.d), NULL, free_strings);
	break;
     default:
	break;
   }
   return (gpointer) (val + 1);
}

test_ArrayUnion *
test_ArrayUnion__alloc(void)
{
   test_ArrayUnion *retval;

   retval =
      ORBit_alloc(sizeof(test_ArrayUnion),
		  (ORBit_free_childvals) test_ArrayUnion__free,
		  GUINT_TO_POINTER(1));
   memset(retval, '\0', sizeof(test_ArrayUnion));
   return retval;
}

CORBA_unsigned_long test_UnionServer__classid = 0;
CORBA_unsigned_long test_AnyServer__classid = 0;
