.\" guname.1 - GNOME version of uname
.\" Copyright 2001  Jochen Voss
.TH guname 1 "Apr 21 2001" "gnome-utils 1.4.0"
.SH NAME
guname \- GNOME version of uname
.SH SYNOPSIS
.B guname
.sp
or select
.B System info ...
from the
.B System
submenu of the Main Menu.
.SH DESCRIPTION
.B Guname
displays a variety of basic information about your system. 

For full documentation see the
.B guname
online help.

.SH AUTHOR
.B Guname
was written by Havoc Pennington (<hp@redhat.com>).

This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.

.SH SEE ALSO
.BR uname (1)
