.\" gfloppy.1 - a graphical frontend for tar
.\" Copyright 2001  Jochen Voss
.TH meat-grinder 1 "Jun 26 2001" "gnome-utils 1.4.0.1"
.SH NAME
meat-grinder \- a graphical front end for tar
.SH SYNOPSIS
.B meat-grinder
.sp
or select
.B Archive Generator
from the
.B Utilities
submenu of the Main Menu.
.SH DESCRIPTION
.B Meat-grinder
is a graphical front end for the tar unix utility.
You can use drag and drop to assemble files and directories
in the
.B meat-grinder
window.  When finished you press a button to pack all the stuff
into a single tar archive.  Very handy!
.P
For full documentation see the
.B meat-grinder
online help.
.SH AUTHOR
.B Meat-grinder
was written by George Lebl (<jirka@5z.com>).
.P
This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.
.SH SEE ALSO
.BR tar (1)
