/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "help-browser.h"

#if ( (TC_IMPL_TC_help_browser_simple_browser_0 == 'h') \
&& (TC_IMPL_TC_help_browser_simple_browser_1 == 'e') \
&& (TC_IMPL_TC_help_browser_simple_browser_2 == 'l') \
&& (TC_IMPL_TC_help_browser_simple_browser_3 == 'p') \
&& (TC_IMPL_TC_help_browser_simple_browser_4 == '_') \
&& (TC_IMPL_TC_help_browser_simple_browser_5 == 'b') \
&& (TC_IMPL_TC_help_browser_simple_browser_6 == 'r') \
&& (TC_IMPL_TC_help_browser_simple_browser_7 == 'o') \
&& (TC_IMPL_TC_help_browser_simple_browser_8 == 'w') \
&& (TC_IMPL_TC_help_browser_simple_browser_9 == 's') \
&& (TC_IMPL_TC_help_browser_simple_browser_10 == 'e') \
&& (TC_IMPL_TC_help_browser_simple_browser_11 == 'r') \
) && !defined(TC_DEF_TC_help_browser_simple_browser)
#define TC_DEF_TC_help_browser_simple_browser 1
const struct CORBA_TypeCode_struct TC_help_browser_simple_browser_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "simple_browser", "IDL:help_browser/simple_browser:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long help_browser_simple_browser__classid = 0;
