/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "Terminal.h"

#if ( (TC_IMPL_TC_GNOME_Terminal_Terminal_0 == 'T') \
&& (TC_IMPL_TC_GNOME_Terminal_Terminal_1 == 'e') \
&& (TC_IMPL_TC_GNOME_Terminal_Terminal_2 == 'r') \
&& (TC_IMPL_TC_GNOME_Terminal_Terminal_3 == 'm') \
&& (TC_IMPL_TC_GNOME_Terminal_Terminal_4 == 'i') \
&& (TC_IMPL_TC_GNOME_Terminal_Terminal_5 == 'n') \
&& (TC_IMPL_TC_GNOME_Terminal_Terminal_6 == 'a') \
&& (TC_IMPL_TC_GNOME_Terminal_Terminal_7 == 'l') \
) && !defined(TC_DEF_TC_GNOME_Terminal_Terminal)
#define TC_DEF_TC_GNOME_Terminal_Terminal 1
const struct CORBA_TypeCode_struct TC_GNOME_Terminal_Terminal_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "Terminal", "IDL:GNOME/Terminal/Terminal:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Terminal_TerminalFactory_0 == 'T') \
&& (TC_IMPL_TC_GNOME_Terminal_TerminalFactory_1 == 'e') \
&& (TC_IMPL_TC_GNOME_Terminal_TerminalFactory_2 == 'r') \
&& (TC_IMPL_TC_GNOME_Terminal_TerminalFactory_3 == 'm') \
&& (TC_IMPL_TC_GNOME_Terminal_TerminalFactory_4 == 'i') \
&& (TC_IMPL_TC_GNOME_Terminal_TerminalFactory_5 == 'n') \
&& (TC_IMPL_TC_GNOME_Terminal_TerminalFactory_6 == 'a') \
&& (TC_IMPL_TC_GNOME_Terminal_TerminalFactory_7 == 'l') \
) && !defined(TC_DEF_TC_GNOME_Terminal_TerminalFactory)
#define TC_DEF_TC_GNOME_Terminal_TerminalFactory 1
const struct CORBA_TypeCode_struct TC_GNOME_Terminal_TerminalFactory_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "TerminalFactory",
      "IDL:GNOME/Terminal/TerminalFactory:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long GNOME_Terminal_Terminal__classid = 0;
CORBA_unsigned_long GNOME_Terminal_TerminalFactory__classid = 0;
