.\" stripchart.1 - GNOME stripchart plotter
.\" Copyright 2001  Jochen Voss
.TH stripchart 1 "Apr 21 2001" "gnome-utils 1.4.0"
.SH NAME
stripchart \- the GNOME stripchart plotter
.SH SYNOPSIS
.B stripchart
.sp
.B stripchart-applet
.sp
or select
.B Stripchart Plotter
from the
.B Utilities
submenu of the Main Menu
.sp
or select
.B Stripchart Plotter
from the
.B Monitors
submenu of the GNOME panel
.B Applets
menu.
.SH DESCRIPTION
The
.B GNOME stripchart
program charts various user-specified parameters
as a function of time. Its main use is to chart system performance
parameters such as CPU load, CPU utilization, network traffic levels,
and the like.
.PP
There is a stand-alone version and a panel applet version
of this program.
.PP
For full documentation see the
.B GNOME stripchart
online help (use the right mouse button).
.SH AUTHOR
The
.B GNOME stripchart
was written by John Kodis (<kodis@jagunet.com>).
.PP
This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.
.SH SEE ALSO
.BR xload (1),
.BR xsysinfo (1x)
