.\" gfontsel.1 - GNOME Font selector
.\" Copyright 2001  Jochen Voss
.TH gfontsel 1 "Apr 16 2001" "gnome-utils 1.4.0"
.SH NAME
gfontsel \- the GNOME Font selector
.SH SYNOPSIS
.B gfontsel
.sp
or select
.B GNOME Font selector
from the
.B Utilities
submenu of the Main Menu.
.SH DESCRIPTION
.B GNOME Font selector
is a simple utility for choosing a screen (i.e. X Window System) font.
It is usually launched automatically when you are changing an
application's font in a Settings or Preferences dialog.

For full documentation see the
.B GNOME Font selector
online help.

.SH AUTHOR
.B GNOME Font selector
was written by Andrew Veliath (<andrewtv@usa.net>) with the help of
many other GNOME developers.

This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.

.SH SEE ALSO
.BR xfontsel (1x),
.BR xlsfonts (1x),
.BR xfd (1x),
and the
.BR "X Logical Font Description" ( "XLFD" )
from the
.I xspecs
package.
