/*
 * bonobo-desktop.idl: Interfaces for desktop elements
 *
 * Copyright (C) 1999  Helix Code, Inc.
 *
 * Author:
 *   Miguel de Icaza (miguel@kernel.org)
 */

#ifndef BONOBO_DESKTOP_IDL
#define BONOBO_DESKTOP_IDL

#include "Bonobo_Unknown.idl"

module Bonobo {

module Desktop {

interface Window : Bonobo::Unknown {

	struct Geometry {
		short x, y;
		short width, height;
	};

	attribute string title;

	Geometry getGeometry ();
	void     setGeometry (in Geometry geo);

	unsigned long getWindowId ();
};

};

};

#endif /* BONOBO_DESKTOP_IDL */
