/*
 * bonobo-advise.idl:
 *
 * Copyright (C) 2000  Helix Code, Inc.
 *
 * Author:
 *	Miguel de Icaza (miguel@helixcode.com)
 */

#ifndef BONOBO_ADVISE_IDL
#define BONOBO_ADVISE_IDL

#include "Bonobo_Unknown.idl"

/*
 *  This interface is deprecated, use the BonoboListener
 * interface instead.
 */

module Bonobo {

	interface AdviseSink : Bonobo::Unknown {
		/**
		 * notify:
		 * @notify_type: an ordinal associated with an event type
		 *
		 * Notifies that some sort of event has occured.
		 */
		void notify (in long notify_type);
		
		/**
		 * notifyRename:
		 * @new_full_name: New name of the server
		 * document.
		 *
		 * Invoked by a server object to notify its
		 * container that now its contents are being
		 * stored in @new_full_name
		 */
		void notifyRename (in string new_full_name);
	};
};

#endif /* BONOBO_ADVISE_IDL */
