/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "gnome-unknown.h"

void
_ORBIT_skel_GNOME_Unknown_ref(POA_GNOME_Unknown * _ORBIT_servant,
			      GIOPRecvBuffer * _ORBIT_recv_buffer,
			      CORBA_Environment * ev,
			      void (*_impl_ref) (PortableServer_Servant
						 _servant,
						 CORBA_Environment * ev))
{
   _impl_ref(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_GNOME_Unknown_unref(POA_GNOME_Unknown * _ORBIT_servant,
				GIOPRecvBuffer * _ORBIT_recv_buffer,
				CORBA_Environment * ev,
				void (*_impl_unref) (PortableServer_Servant
						     _servant,
						     CORBA_Environment * ev))
{
   _impl_unref(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_GNOME_Unknown_query_interface(POA_GNOME_Unknown * _ORBIT_servant,
					  GIOPRecvBuffer * _ORBIT_recv_buffer,
					  CORBA_Environment * ev,
					  CORBA_Object(*_impl_query_interface)
					  (PortableServer_Servant _servant,
					   const CORBA_char * repoid,
					   CORBA_Environment * ev))
{
   CORBA_Object _ORBIT_retval;
   CORBA_char *repoid;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 repoid = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(repoid[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 repoid = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(repoid[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _ORBIT_retval = _impl_query_interface(_ORBIT_servant, repoid, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    ORBit_marshal_object(_ORBIT_send_buffer, _ORBIT_retval);
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      if (ev->_major == CORBA_NO_EXCEPTION)
	 CORBA_Object_release(_ORBIT_retval, ev);
   }
}
static ORBitSkeleton
get_skel_GNOME_Unknown(POA_GNOME_Unknown * servant,
		       GIOPRecvBuffer * _ORBIT_recv_buffer, gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'q':
	if (strcmp((opname + 1), "uery_interface"))
	   break;
	*impl = (gpointer) servant->vepv->GNOME_Unknown_epv->query_interface;
	return (ORBitSkeleton) _ORBIT_skel_GNOME_Unknown_query_interface;
	break;
     case 'r':
	if (strcmp((opname + 1), "ef"))
	   break;
	*impl = (gpointer) servant->vepv->GNOME_Unknown_epv->ref;
	return (ORBitSkeleton) _ORBIT_skel_GNOME_Unknown_ref;
	break;
     case 'u':
	if (strcmp((opname + 1), "nref"))
	   break;
	*impl = (gpointer) servant->vepv->GNOME_Unknown_epv->unref;
	return (ORBitSkeleton) _ORBIT_skel_GNOME_Unknown_unref;
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_GNOME_Unknown(CORBA_Object obj, POA_GNOME_Unknown * servant)
{
   obj->vepv[GNOME_Unknown__classid] = servant->vepv->GNOME_Unknown_epv;
}

void
POA_GNOME_Unknown__init(PortableServer_Servant servant,
			CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_GNOME_Unknown, "IDL:GNOME/Unknown:1.0",
(ORBit_local_objref_init) & init_local_objref_GNOME_Unknown };
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!GNOME_Unknown__classid)
      GNOME_Unknown__classid = ORBit_register_class(&class_info);
}

void
POA_GNOME_Unknown__fini(PortableServer_Servant servant,
			CORBA_Environment * env)
{
   PortableServer_ServantBase__fini(servant, env);
}
