/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "gnome-factory.h"

#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'g') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == 'c') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_10 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_11 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_12 == 'y') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array2[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array2,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'g') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == 'c') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_10 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_11 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_12 == 'y') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array11[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array11,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_stringlist_0 == 'g') \
&& (TC_IMPL_TC_GNOME_stringlist_1 == 'n') \
&& (TC_IMPL_TC_GNOME_stringlist_2 == 'o') \
&& (TC_IMPL_TC_GNOME_stringlist_3 == 'm') \
&& (TC_IMPL_TC_GNOME_stringlist_4 == 'e') \
&& (TC_IMPL_TC_GNOME_stringlist_5 == '_') \
&& (TC_IMPL_TC_GNOME_stringlist_6 == 'f') \
&& (TC_IMPL_TC_GNOME_stringlist_7 == 'a') \
&& (TC_IMPL_TC_GNOME_stringlist_8 == 'c') \
&& (TC_IMPL_TC_GNOME_stringlist_9 == 't') \
&& (TC_IMPL_TC_GNOME_stringlist_10 == 'o') \
&& (TC_IMPL_TC_GNOME_stringlist_11 == 'r') \
&& (TC_IMPL_TC_GNOME_stringlist_12 == 'y') \
) && !defined(TC_DEF_TC_GNOME_stringlist)
#define TC_DEF_TC_GNOME_stringlist 1
static const CORBA_TypeCode anon_subtypes_array15[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_GNOME_stringlist_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "stringlist", "IDL:GNOME/stringlist:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array15,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_GenericFactory_0 == 'g') \
&& (TC_IMPL_TC_GNOME_GenericFactory_1 == 'n') \
&& (TC_IMPL_TC_GNOME_GenericFactory_2 == 'o') \
&& (TC_IMPL_TC_GNOME_GenericFactory_3 == 'm') \
&& (TC_IMPL_TC_GNOME_GenericFactory_4 == 'e') \
&& (TC_IMPL_TC_GNOME_GenericFactory_5 == '_') \
&& (TC_IMPL_TC_GNOME_GenericFactory_6 == 'f') \
&& (TC_IMPL_TC_GNOME_GenericFactory_7 == 'a') \
&& (TC_IMPL_TC_GNOME_GenericFactory_8 == 'c') \
&& (TC_IMPL_TC_GNOME_GenericFactory_9 == 't') \
&& (TC_IMPL_TC_GNOME_GenericFactory_10 == 'o') \
&& (TC_IMPL_TC_GNOME_GenericFactory_11 == 'r') \
&& (TC_IMPL_TC_GNOME_GenericFactory_12 == 'y') \
) && !defined(TC_DEF_TC_GNOME_GenericFactory)
#define TC_DEF_TC_GNOME_GenericFactory 1
const struct CORBA_TypeCode_struct TC_GNOME_GenericFactory_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "GenericFactory", "IDL:GNOME/GenericFactory:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_GenericFactory_CannotActivate_0 == 'g') \
&& (TC_IMPL_TC_GNOME_GenericFactory_CannotActivate_1 == 'n') \
&& (TC_IMPL_TC_GNOME_GenericFactory_CannotActivate_2 == 'o') \
&& (TC_IMPL_TC_GNOME_GenericFactory_CannotActivate_3 == 'm') \
&& (TC_IMPL_TC_GNOME_GenericFactory_CannotActivate_4 == 'e') \
&& (TC_IMPL_TC_GNOME_GenericFactory_CannotActivate_5 == '_') \
&& (TC_IMPL_TC_GNOME_GenericFactory_CannotActivate_6 == 'f') \
&& (TC_IMPL_TC_GNOME_GenericFactory_CannotActivate_7 == 'a') \
&& (TC_IMPL_TC_GNOME_GenericFactory_CannotActivate_8 == 'c') \
&& (TC_IMPL_TC_GNOME_GenericFactory_CannotActivate_9 == 't') \
&& (TC_IMPL_TC_GNOME_GenericFactory_CannotActivate_10 == 'o') \
&& (TC_IMPL_TC_GNOME_GenericFactory_CannotActivate_11 == 'r') \
&& (TC_IMPL_TC_GNOME_GenericFactory_CannotActivate_12 == 'y') \
) && !defined(TC_DEF_TC_GNOME_GenericFactory_CannotActivate)
#define TC_DEF_TC_GNOME_GenericFactory_CannotActivate 1
const struct CORBA_TypeCode_struct
   TC_GNOME_GenericFactory_CannotActivate_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "CannotActivate",
      "IDL:GNOME/GenericFactory/CannotActivate:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_string_0 == 'g') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_1 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_3 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_4 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_5 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_6 == 'f') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_7 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_8 == 'c') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_9 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_10 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_11 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_12 == 'y') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_string)
#define ORBIT_DEF_CORBA_sequence_CORBA_string 1

gpointer
CORBA_sequence_CORBA_string__free(gpointer mem, gpointer dat,
				  CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_string *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CORBA_string *
CORBA_sequence_CORBA_string__alloc(void)
{
   CORBA_sequence_CORBA_string *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_string),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_string__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CORBA_char **
CORBA_sequence_CORBA_string_allocbuf(CORBA_unsigned_long len)
{
   CORBA_char **retval =
      ORBit_alloc(sizeof(CORBA_char *) * len,
		  (ORBit_free_childvals) CORBA_string__free,
		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(CORBA_char *) * len);
   return retval;
}
#endif

gpointer
GNOME_stringlist__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   return CORBA_sequence_CORBA_string__free(mem, dat, free_strings);
}

GNOME_stringlist *
GNOME_stringlist__alloc(void)
{
   return CORBA_sequence_CORBA_string__alloc();
}

gpointer
GNOME_GenericFactory_CannotActivate__free(gpointer mem, gpointer dat,
					  CORBA_boolean free_strings)
{
   GNOME_GenericFactory_CannotActivate *var = mem;

   return (gpointer) (var + 1);
}

CORBA_unsigned_long GNOME_GenericFactory__classid = 0;
