/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "gnome-unknown.h"

#if ( (TC_IMPL_TC_GNOME_Unknown_0 == 'g') \
&& (TC_IMPL_TC_GNOME_Unknown_1 == 'n') \
&& (TC_IMPL_TC_GNOME_Unknown_2 == 'o') \
&& (TC_IMPL_TC_GNOME_Unknown_3 == 'm') \
&& (TC_IMPL_TC_GNOME_Unknown_4 == 'e') \
&& (TC_IMPL_TC_GNOME_Unknown_5 == '_') \
&& (TC_IMPL_TC_GNOME_Unknown_6 == 'u') \
&& (TC_IMPL_TC_GNOME_Unknown_7 == 'n') \
&& (TC_IMPL_TC_GNOME_Unknown_8 == 'k') \
&& (TC_IMPL_TC_GNOME_Unknown_9 == 'n') \
&& (TC_IMPL_TC_GNOME_Unknown_10 == 'o') \
&& (TC_IMPL_TC_GNOME_Unknown_11 == 'w') \
&& (TC_IMPL_TC_GNOME_Unknown_12 == 'n') \
) && !defined(TC_DEF_TC_GNOME_Unknown)
#define TC_DEF_TC_GNOME_Unknown 1
const struct CORBA_TypeCode_struct TC_GNOME_Unknown_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "Unknown", "IDL:GNOME/Unknown:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long GNOME_Unknown__classid = 0;
