.TH MEDUSA-FILE-INDEX-STOPLIST 5 "February 8, 2001" Eazel
.SH NAME
medusa-file-index-stoplist \- list of paths excluded from medusa indices
.SH SYNOPSIS
/usr//etc/medusa/file-index-stoplist
.SH DESCRIPTION
.B /usr//etc/medusa/file-index-stoplist
contains a list of paths that will be ignored by
.B medusa-indexd
when creating file system indices.
They should be in URI form,
one per line.
Lines beginning with the number sign (#) are
considered to be comments and are ignored.
.SH EXAMPLE
# Exclude /proc and /dev
.br
file:///proc
.br
file:///dev
.SH SEE ALSO
.BR medusa-indexd (8)
