.TH MEDUSA.CONF 5 "February 8, 2001" Eazel
.SH NAME
medusa.conf \- Configuration file for the medusa index and search service
.SH SYNOPSIS
/usr//etc/medusa/medusa.conf
.SH DESCRIPTION
.B /usr//etc/medusa/medusa.conf
current contains one option, which allows system administrators to block medusa usage on the
system, so that no user can turn it on. The "blocked" option is off by default.  Setting
it to "yes" will prevent any user, including root from using nautilus or  
.B medusa-enable-indexing
to turn indexing and indexed searches on for a system.
.SH SEE ALSO
.BR medusa-indexd (8) 
.BR medusa-searchd (8)
