.TH MEDUSA-CONFIG 1 "February 8, 2001" Eazel
.SH NAME
medusa-config \- get compilation options needed to use medusa libraries
.SH SYNOPSIS
.TP
.B medusa-config
[
.BI \-\-prefix= directory
]
[
.BI \-\-exec_prefix= directory
]
.B \-\-cflags
\(bv
.B \-\-libs
\(bv
.B --prefix
\(bv
.B --exec-prefix
\(bv
.B \-\-version
\(bv
.B \-\-help
.SH DESCRIPTION
.B medusa-config
provides information about the command line options needed to use
the
.B medusa
libraries.
.LP
These options change
.BR medusa-config 's
idea of the installation prefix:
.TP
.BI \-\-prefix= directory
Act as if
.B medusa
files
had been installed into the specified directory
.TP
.BI \-\-exec_prefix= directory
Act as if
.B medusa
executables
had been installed into the specified directory
.LP
These options specify what you want
.B medusa-config
to report.
At least one of these must be specified.
.TP
.BI \-\-cflags
Report the flags that need to be given to the C compiler to
use the
.B medusa
libraries
.TP
.BI \-\-libs
Report the flags that need to be given to the C compiler to
link against the
.B medusa
libraries
.TP
.BI \-\-prefix
Report the prefix directory into which the
.B medusa
files
were installed
.TP
.BI \-\-exec_prefix
Report the prefix directory into which the
.B medusa
executables
were installed.
.TP
.B \-\-version
Report the version of
.B medusa
that is installed
.LP
This option provides information about
.B medusa-config
itself:
.TP
.B \-\-help
Summarize the options available for
.BR medusa-config .
.SH SEE ALSO
.BR libmedusa (3)
