.TH MSEARCH 1 "February 8, 2001" Eazel
.SH NAME
msearch \- perform a medusa search
.SH SYNOPSIS
.B msearch
.I search-uri
.SH DESCRIPTION
.B msearch
connects to
.B medusa-searchd
to retrieve a list of files matching the specified
.IR search-uri .
The results are printed to the standard output, one file
per line.
.LP
See
.BR medusa-search-uri (7)
for the details of how to form the
.IR search-uri .
.SH SEE ALSO
.BR medusa-searchd (8),
.BR medusa-search-uri (7) .
