#ifndef __GNOME_UNKNOWN_IDL__
#define __GNOME_UNKNOWN_IDL__

#if !defined(__LIBGNORBA_COMPILATION) && defined(__ORBIT_IDL__)
%{
#pragma include_defs libgnorba/gnome-unknown.h
%}
#pragma inhibit push
#endif

module GNOME {
	interface Unknown {
		/**
		 * ref:
		 *
		 * increments the reference count
		 */
		void ref ();
		/**
		 * unref:
		 * 
		 * decrements the reference count
		 */
		void unref ();
		
		Object query_interface (in string repoid);
	};
};

#if !defined(__LIBGNORBA_COMPILATION) && defined(__ORBIT_IDL__)
#pragma inhibit pop
#endif

#endif


