/* Automatically generated by po2tbl.sed from scrollkeeper.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"wrong content list file %s\n", 2},
  {"wrong extended content list file %s\n", 3},
  {"\
Usage: scrollkeeper_install [-v] [-p <SCROLLKEEPER_DB_DIR>] <OMF FILE>\n", 4},
  {"wrong omf file %s\n", 5},
  {"Usage: scrollkeeper_preinstall <DOC FILE> <OMF FILE> <NEW OMF FILE>\n", 6},
  {"%s missing\n", 7},
  {"\
Usage: scrollkeeper_uninstall [-v] [-p <SCROLLKEEPER_DB_DIR>] <OMF FILE>\n", 8},
  {"Usage: %s [-v] [-p <SCROLLKEEPER_DB_DIR>] [-o <OMF_DIR>]\n", 9},
  {"%s: warning: %s overrides %s\n", 10},
  {"Unable to create database directory: %s\n", 11},
  {"%s: %s: is not a directory\n", 12},
  {"Usage: %s [-v] <LOCALE> <CATEGORY TREE FILE NAME>\n", 13},
  {"No Content List for this locale!!!\n", 14},
  {"error while parsing %s\n", 15},
  {"\
Usage:  toc <filename>\n\
\n", 16},
  {"%s: out of memory: %s\n", 17},
};

int _msg_tbl_length = 17;
