/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define __IDL_const const
#else
#define __IDL_const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN __IDL__start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((__IDL__start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE __IDL_restart( __IDL_in )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct __IDL__buffer_state *YY_BUFFER_STATE;

extern int __IDL_leng;
extern FILE *__IDL_in, *__IDL_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		__IDL_less( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the __IDL_less() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define __IDL_less(n) \
	do \
		{ \
		/* Undo effects of setting up __IDL_text. */ \
		*__IDL__cp = __IDL__hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		__IDL__c_buf_p = __IDL__cp = __IDL__bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up __IDL_text again */ \
		} \
	while ( 0 )

#define unput(c) __IDL_unput( c, __IDL_text_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int __IDL__size_t;


struct __IDL__buffer_state
	{
	FILE *__IDL__input_file;

	char *__IDL__ch_buf;		/* input buffer */
	char *__IDL__buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	__IDL__size_t __IDL__buf_size;

	/* Number of characters read into __IDL__ch_buf, not including EOB
	 * characters.
	 */
	int __IDL__n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int __IDL__is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int __IDL__is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int __IDL__at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int __IDL__fill_buffer;

	int __IDL__buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via __IDL_restart()), so that the user can continue scanning by
	 * just pointing __IDL_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE __IDL__current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER __IDL__current_buffer


/* __IDL__hold_char holds the character lost when __IDL_text is formed. */
static char __IDL__hold_char;

static int __IDL__n_chars;		/* number of characters read into __IDL__ch_buf */


int __IDL_leng;

/* Points to current character in buffer. */
static char *__IDL__c_buf_p = (char *) 0;
static int __IDL__init = 1;		/* whether we need to initialize */
static int __IDL__start = 0;	/* start state number */

/* Flag which is used to allow __IDL_wrap()'s to do buffer switches
 * instead of setting up a fresh __IDL_in.  A bit of a hack ...
 */
static int __IDL__did_buffer_switch_on_eof;

void __IDL_restart YY_PROTO(( FILE *input_file ));

void __IDL__switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void __IDL__load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE __IDL__create_buffer YY_PROTO(( FILE *file, int size ));
void __IDL__delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void __IDL__init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void __IDL__flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER __IDL__flush_buffer( __IDL__current_buffer )

YY_BUFFER_STATE __IDL__scan_buffer YY_PROTO(( char *base, __IDL__size_t size ));
YY_BUFFER_STATE __IDL__scan_string YY_PROTO(( __IDL_const char *__IDL__str ));
YY_BUFFER_STATE __IDL__scan_bytes YY_PROTO(( __IDL_const char *bytes, int len ));

static void *__IDL__flex_alloc YY_PROTO(( __IDL__size_t ));
static void *__IDL__flex_realloc YY_PROTO(( void *, __IDL__size_t ));
static void __IDL__flex_free YY_PROTO(( void * ));

#define __IDL__new_buffer __IDL__create_buffer

#define __IDL__set_interactive(is_interactive) \
	{ \
	if ( ! __IDL__current_buffer ) \
		__IDL__current_buffer = __IDL__create_buffer( __IDL_in, YY_BUF_SIZE ); \
	__IDL__current_buffer->__IDL__is_interactive = is_interactive; \
	}

#define __IDL__set_bol(at_bol) \
	{ \
	if ( ! __IDL__current_buffer ) \
		__IDL__current_buffer = __IDL__create_buffer( __IDL_in, YY_BUF_SIZE ); \
	__IDL__current_buffer->__IDL__at_bol = at_bol; \
	}

#define YY_AT_BOL() (__IDL__current_buffer->__IDL__at_bol)

typedef unsigned char YY_CHAR;
FILE *__IDL_in = (FILE *) 0, *__IDL_out = (FILE *) 0;
typedef int __IDL__state_type;
extern char *__IDL_text;
#define __IDL_text_ptr __IDL_text

static __IDL__state_type __IDL__get_previous_state YY_PROTO(( void ));
static __IDL__state_type __IDL__try_NUL_trans YY_PROTO(( __IDL__state_type current_state ));
static int __IDL__get_next_buffer YY_PROTO(( void ));
static void __IDL__fatal_error YY_PROTO(( __IDL_const char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up __IDL_text.
 */
#define YY_DO_BEFORE_ACTION \
	__IDL_text_ptr = __IDL__bp; \
	__IDL_leng = (int) (__IDL__cp - __IDL__bp); \
	__IDL__hold_char = *__IDL__cp; \
	*__IDL__cp = '\0'; \
	__IDL__c_buf_p = __IDL__cp;

#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
static __IDL_const short int __IDL__accept[347] =
    {   0,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        3,    3,   69,   67,    6,   64,   67,   67,   67,   67,
       67,    7,    8,   67,   67,   67,   55,   55,   55,   55,
       67,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,    6,    5,
       67,   67,   67,   59,   58,   67,    6,   64,   67,    6,
        5,    3,    3,    3,    3,    3,    3,    6,    0,   63,
        0,   62,    0,   11,   66,   65,   11,    7,   10,    0,
        0,    8,   51,   53,   52,   55,   57,   55,   55,   55,
       56,   56,   55,   55,   55,   55,   55,   55,   55,   55,

       55,   55,   55,   55,   28,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,    6,    5,    5,    5,    5,    1,    0,    0,
       59,    0,   61,    6,   66,   65,    6,    5,    5,    5,
        5,    5,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    2,    0,    0,    0,   65,   11,    0,   11,    9,
       55,   55,   55,   56,   15,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   36,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,    5,    1,   47,   60,

       65,   61,    5,    3,    3,    2,    0,    0,   11,   55,
       55,   14,   56,   55,   55,   18,   19,   55,   55,   55,
       55,   24,   55,   55,   55,   55,   55,   31,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   48,   55,   55,    5,    5,    3,   12,   55,
       56,   55,   55,   20,   55,   55,   55,   55,   26,   27,
       29,   55,   55,   55,   34,   55,   55,   55,   55,   40,
       55,   55,   55,   55,   45,   55,   49,   55,    5,    5,
        3,   13,   56,   55,   55,   55,   55,   23,   55,   55,
       32,   33,   35,   37,   55,   55,   41,   42,   43,   55,

       55,   55,    5,    5,    3,   56,   55,   17,   21,   22,
       55,   55,   55,   55,   44,   55,   50,    4,    4,    3,
       56,   55,   55,   55,   38,   39,   46,    4,    4,    4,
        4,    4,    3,    3,   56,   16,   25,   30,   56,    0,
        0,    0,   54,    0,    0,    0
    } ;

static __IDL_const int __IDL__ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    6,    1,    7,    8,
        9,   10,    1,    1,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,   17,
        1,   18,    1,    1,   19,   20,   20,   21,   22,   23,
       24,   24,   24,   24,   24,   25,   24,   24,   26,   24,
       24,   27,   28,   29,   30,   24,   24,   31,   24,   24,
        1,    1,   32,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   24,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   24,   58,    1,   59,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static __IDL_const int __IDL__meta[60] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    4,    1,
        1,    1,    1,    5,    5,    1,    1,    1,    6,    6,
        6,    6,    6,    7,    7,    7,    7,    7,    7,    7,
        7,    1,    8,    6,    6,    6,    6,    6,    6,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    1
    } ;

static __IDL_const short int __IDL__base[372] =
    {   0,
        0,   58,  880,   60,   72,  131,   89,   94,    0,   65,
       98,  107,  891,  893,  888,  893,   65,  111,   79,  101,
      109,  179,  138,  873,  871,  869,  853,  132,   73,   90,
      852,  121,  122,  137,  139,  141,  124,  146,  148,  149,
       91,  152,  169,  171,  123,  173,  166,  178,  124,  160,
      826,  206,    0,    0,  893,  874,  119,  873,  215,  225,
      229,    0,  879,  148,  231,  213,  821,  877,  236,  893,
      234,  893,  230,  232,  893,    0,  234,  261,  893,  248,
        0,  266,  893,  893,  893,  845,    0,  225,  231,  227,
        0,  840,  232,  233,  246,  235,  257,  251,  261,  259,

      262,  269,  263,  273,  274,  268,  276,  275,  277,  278,
      284,  210,  289,  285,  291,  292,  295,  297,  298,  299,
      302,  300,  342,  337,    0,  344,  826,    0,  863,  865,
        0,  864,  893,  346,  863,  347,  349,  357,  354,  359,
        0,  361,    0,  869,    0,    0,  367,  351,    0,  365,
      820,    0,  359,  363,  368,    0,  372,  374,  376,    0,
      343,  364,  373,  831,  835,  348,  368,  370,  371,  381,
      382,  384,  385,  387,  389,  390,  393,  396,  395,  398,
      403,  404,  405,  834,  406,  407,  408,  414,  410,  415,
      416,  422,  417,  425,  432,  420,  832,    0,  893,  893,

      465,    0,  468,    0,  831,    0,  458,  461,  466,  456,
      449,  831,  827,  450,  453,  829,  828,  451,  455,  454,
      457,  827,  461,  463,  464,  465,  471,  826,  466,  472,
      473,  478,  475,  481,  482,  485,  486,  491,  497,  498,
      490,  489,  825,  501,  505,  817,  536,  816,  822,  507,
      810,  508,  515,  820,  509,  511,  519,  517,  819,  818,
      817,  521,  520,  523,  816,  513,  529,  531,  533,  815,
      534,  530,  540,  545,  814,  538,  813,  539,  798,  583,
      789,  785,  759,  535,  554,  542,  556,  769,  557,  562,
      753,  739,  731,  723,  558,  565,  696,  687,  635,  564,

      571,  572,  633,  604,  632,  617,  573,  631,  627,  625,
      577,  578,  560,  582,  623,  585,  615,  643,  624,  635,
      597,  583,  586,  596,  598,  590,  423,    0,  363,  627,
      637,    0,    0,  220,  147,   94,   62,   28,  639,  641,
      648,  650,  893,  652,  660,  893,  669,  677,  685,  693,
      701,  705,  709,  717,  725,  729,  737,  745,  753,  761,
      769,  773,  775,  783,  791,  799,  807,  815,  823,  831,
      838
    } ;

static __IDL_const short int __IDL__def[372] =
    {   0,
      346,    1,    1,    1,  347,  347,  348,  348,    1,    1,
      349,  349,  346,  346,  346,  346,  350,  351,  346,  346,
      346,  346,  346,  346,  346,  346,  352,  352,  352,  352,
      353,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  346,  354,
      346,  346,  355,  356,  346,  357,  357,  357,  357,  357,
      358,  359,  359,  359,  359,  360,  359,  346,  350,  346,
      351,  346,  346,  346,  346,  361,  346,  346,  346,  346,
      362,  346,  346,  346,  346,  352,  363,  352,  352,  352,
      353,  353,  352,  352,  352,  352,  352,  352,  352,  352,

      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  346,  354,  354,  354,  354,  364,  346,  355,
      356,  357,  346,  357,  357,  365,  357,  358,  358,  358,
      354,  358,  359,  359,  359,  366,  359,  360,  360,  360,
      360,  367,  346,  346,  346,  361,  346,  346,  346,  362,
      352,  352,  352,  353,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  354,  364,  346,  346,

      365,  361,  358,  366,  360,  367,  346,  346,  346,  352,
      352,  352,  353,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  354,  358,  360,  352,  352,
      353,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  354,  358,
      360,  352,  353,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,

      352,  352,  354,  358,  360,  353,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  368,  369,  370,
      353,  352,  352,  352,  352,  352,  352,  368,  368,  369,
      369,  368,  370,  370,  353,  352,  352,  352,  353,  346,
      371,  371,  346,  371,  346,    0,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346
    } ;

static __IDL_const short int __IDL__nxt[953] =
    {   0,
       14,   15,   16,   17,   14,   14,   18,   14,   14,   14,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   27,
       27,   27,   28,   27,   27,   29,   27,   27,   30,   27,
       27,   14,   31,   32,   33,   34,   35,   36,   37,   27,
       27,   38,   27,   39,   40,   41,   42,   27,   27,   43,
       44,   45,   46,   47,   48,   27,   27,   14,   14,   49,
       87,   49,   50,   51,   50,   51,   49,   70,   70,   50,
       51,   52,   14,   15,   16,   14,   14,   14,   14,   53,
       14,   14,   14,   14,   21,   14,   14,   14,   14,   14,
       57,   58,   73,   73,   87,   60,   58,   14,   61,   63,

       16,   59,   14,   55,   14,   87,   59,   89,   65,   16,
       64,   66,   67,   72,   74,   74,   90,   72,   75,   64,
      134,   76,   87,   87,  108,  123,   87,  133,  124,   14,
       14,   14,   49,   16,   14,   50,   14,   14,   53,   14,
       14,   14,   14,   21,   14,   14,   14,   14,   14,   77,
       88,   82,   82,   87,   87,   87,   87,  145,   79,   80,
      146,  126,   55,   14,   87,  103,   93,  104,   95,   87,
       96,   87,   94,   87,   79,   80,   99,   97,   87,  118,
       87,   87,  339,   98,   87,  100,  101,  109,   14,   14,
       77,  105,   78,   78,  106,  107,  102,  110,   87,   79,

       80,   87,  112,   87,  111,   87,  113,  127,  114,   81,
       87,  115,  120,  121,  150,   79,   80,  129,  119,   74,
       74,  334,  116,  133,  135,  117,  137,  136,  122,  138,
      140,  132,  147,  133,   81,  148,   72,  141,   70,   70,
       72,  153,   87,  154,  154,   74,   74,  157,  157,  161,
       79,  185,   79,  155,   79,   80,  163,   87,  158,   87,
      151,  159,  159,   87,   87,   87,   79,   87,   79,  155,
       79,   80,   77,  162,   78,   78,  142,   77,   87,   82,
       82,   79,   80,   87,  166,  168,   79,   80,  165,   87,
      169,   87,  167,   87,   87,   87,  170,   79,   80,  171,

       87,   87,   79,   80,  174,   87,   87,   87,   87,   87,
       87,  172,  180,  179,  173,  183,   87,   87,  175,  176,
      177,   87,  186,   87,   87,  178,  181,   87,  182,   87,
       87,   87,   87,  187,   87,  184,  190,  188,  126,  192,
      194,  189,  195,  123,  191,  126,  124,  134,  193,  132,
      137,  196,  150,  138,  133,  202,  132,  133,  140,  132,
      140,  132,  141,  132,  329,  141,  150,  141,  147,  141,
      210,  148,  207,  207,  153,   87,  154,  154,  208,   79,
       87,  209,  209,   79,  127,  157,  157,  159,  159,  159,
      159,  127,   79,  155,  212,   79,   87,  214,  151,   79,

       87,  211,   87,   87,  142,   87,  142,  216,   79,  155,
      203,  215,  151,   87,   87,  220,   87,   87,  221,   87,
      217,   87,   87,  225,  223,   87,  224,   87,   87,  222,
       87,  218,  219,  227,  228,   87,   87,   87,   87,   87,
       87,  231,   87,  234,  230,  226,   87,   87,   87,   87,
      229,  237,   87,  240,   87,   87,  233,   87,  242,  232,
      235,  243,  238,  236,   87,  244,  239,  132,  241,  245,
      132,  207,  207,  202,  209,  209,  141,  249,   79,  209,
      209,   87,   87,   87,  250,   87,   87,   87,   87,   87,
      253,  252,  255,   87,   79,   87,   87,   87,   87,  259,

      257,  247,  254,   87,   87,   87,  256,   87,  258,  263,
       87,  266,  267,   87,   87,  260,  261,   87,   87,  269,
      262,   87,   87,   87,  265,  264,  272,  268,  276,   87,
       87,  271,  273,   87,  274,  275,  270,   87,  132,   87,
       87,   87,  284,   87,  141,   87,  278,   87,  285,   87,
      277,   87,   87,   87,  287,   87,  288,  291,  282,  290,
      292,   87,   87,   87,  286,   87,   87,   87,  289,  293,
       87,   87,   87,  297,   87,  280,  295,   87,  296,  294,
      299,  298,  300,  301,  302,  132,   87,  307,   87,   87,
       87,  141,   87,  309,   87,  312,   87,   87,  311,  308,

      314,  313,  315,   87,   87,   87,  132,  310,  316,   87,
       87,  317,  141,  324,   87,   87,  325,   87,   87,  326,
      336,  327,   87,  323,  322,  331,  132,  304,   87,  132,
       87,  337,  332,  338,  335,  332,  334,  319,  331,  132,
      340,  340,  340,  340,  329,  332,  341,   87,  341,  342,
      342,  342,  342,  345,  345,   87,  343,   87,  343,   87,
      343,  345,  345,   87,  321,  320,  318,   87,  343,   54,
       54,   54,   54,   54,   54,   54,   54,   56,   56,   56,
       56,   56,   56,   56,   56,   62,   62,   62,   62,   62,
       62,   62,   62,   69,   69,   69,   69,   69,   69,   69,

       69,   71,   71,   71,   71,   71,   71,   71,   71,   86,
       86,   86,   86,   91,   91,   91,   91,  125,  125,   87,
      125,  125,  125,  125,  125,  130,  130,  130,   87,  130,
      130,  130,  130,  131,  131,  131,  131,  132,  132,  132,
      132,  132,  132,  132,  132,  139,  139,  139,  139,  139,
      139,  139,  139,  143,  143,   87,  143,  143,  143,  143,
      143,  149,  149,   87,  149,  149,  149,  149,  149,  156,
      156,   87,  156,  156,  156,  156,  156,  160,  160,   87,
       87,   87,   87,  198,  198,   87,  198,  198,  198,  198,
      198,  201,  201,  201,  201,  201,  201,  201,  201,  204,

      204,   87,  204,  204,  204,  204,  204,  206,  206,  306,
      206,  206,  206,  206,  206,  328,  328,   87,  328,  328,
      328,  328,  328,  330,  330,  330,  330,  330,  330,  330,
      330,  333,  333,  305,  333,  333,  333,  333,  333,  344,
      344,  344,  303,  344,  344,   87,   87,   87,   87,   87,
       87,   87,   87,  283,   87,  281,  279,   87,   87,   87,
       87,   87,  251,   87,  248,  246,   87,   87,  213,  205,
      144,  133,  133,  200,  199,  197,  164,   87,   68,  152,
      144,  133,  133,  128,   92,   87,   85,   84,   83,   68,
      346,   52,   13,  346,  346,  346,  346,  346,  346,  346,

      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346
    } ;

static __IDL_const short int __IDL__chk[953] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
      338,    4,    2,    2,    4,    4,   10,   17,   17,   10,
       10,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        7,    7,   19,   19,  337,    8,    8,    7,    8,   11,

       11,    7,    8,    5,    5,   29,    8,   29,   12,   12,
       11,   12,   12,   18,   20,   20,   30,   18,   21,   12,
       57,   21,   30,   41,   41,   49,  336,   57,   49,    5,
        5,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,   23,
       28,   23,   23,   32,   33,   45,   37,   64,   23,   23,
       64,   50,    6,    6,   28,   37,   32,   37,   33,   34,
       34,   35,   32,   36,   23,   23,   35,   34,   38,   45,
       39,   40,  335,   34,   42,   35,   36,   42,    6,    6,
       22,   38,   22,   22,   39,   40,   36,   42,   47,   22,

       22,   43,   43,   44,   42,   46,   43,   50,   44,   22,
       48,   44,   47,   48,   66,   22,   22,   52,   46,   52,
       52,  334,   44,   59,   59,   44,   60,   59,   48,   60,
       61,   61,   65,   60,   22,   65,   71,   61,   69,   69,
       71,   73,  112,   73,   73,   74,   74,   77,   77,   88,
       73,  112,   74,   74,   77,   77,   90,   88,   80,   90,
       66,   80,   80,   89,   93,   94,   73,   96,   74,   74,
       77,   77,   78,   89,   78,   78,   61,   82,   95,   82,
       82,   78,   78,   98,   94,   96,   82,   82,   93,   97,
       97,  100,   95,   99,  101,  103,   98,   78,   78,   99,

      106,  102,   82,   82,  102,  104,  105,  108,  107,  109,
      110,  100,  107,  106,  101,  110,  111,  114,  103,  104,
      105,  113,  113,  115,  116,  105,  108,  117,  109,  118,
      119,  120,  122,  114,  121,  111,  117,  115,  124,  119,
      120,  116,  121,  123,  118,  126,  123,  134,  119,  136,
      137,  122,  148,  137,  134,  136,  139,  137,  138,  138,
      140,  140,  139,  142,  329,  138,  150,  140,  147,  142,
      161,  147,  153,  153,  154,  161,  154,  154,  155,  153,
      166,  155,  155,  154,  124,  157,  157,  158,  158,  159,
      159,  126,  157,  157,  163,  153,  162,  166,  148,  154,

      167,  162,  168,  169,  138,  163,  140,  168,  157,  157,
      142,  167,  150,  170,  171,  171,  172,  173,  172,  174,
      169,  175,  176,  176,  174,  177,  175,  179,  178,  173,
      180,  170,  170,  178,  179,  181,  182,  183,  185,  186,
      187,  182,  189,  186,  181,  177,  188,  190,  191,  193,
      180,  189,  196,  191,  192,  327,  185,  194,  193,  183,
      187,  194,  189,  188,  195,  195,  190,  201,  192,  196,
      203,  207,  207,  201,  208,  208,  203,  210,  207,  209,
      209,  211,  214,  218,  211,  215,  220,  219,  210,  221,
      215,  214,  219,  223,  207,  224,  225,  226,  229,  224,

      221,  203,  218,  227,  230,  231,  220,  233,  223,  229,
      232,  232,  233,  234,  235,  225,  226,  236,  237,  235,
      227,  242,  241,  238,  231,  230,  238,  234,  242,  239,
      240,  237,  239,  244,  240,  241,  236,  245,  247,  250,
      252,  255,  252,  256,  247,  266,  245,  253,  253,  258,
      244,  257,  263,  262,  256,  264,  257,  263,  250,  262,
      264,  267,  272,  268,  255,  269,  271,  284,  258,  266,
      276,  278,  273,  271,  286,  247,  268,  274,  269,  267,
      273,  272,  274,  276,  278,  280,  285,  284,  287,  289,
      295,  280,  313,  286,  290,  290,  300,  296,  289,  285,

      296,  295,  300,  301,  302,  307,  304,  287,  301,  311,
      312,  302,  304,  312,  314,  322,  313,  316,  323,  314,
      322,  316,  326,  311,  307,  319,  319,  280,  324,  330,
      325,  323,  319,  324,  321,  330,  320,  304,  331,  331,
      339,  339,  340,  340,  318,  331,  339,  317,  340,  341,
      341,  342,  342,  344,  344,  315,  341,  310,  342,  309,
      344,  345,  345,  308,  306,  305,  303,  299,  345,  347,
      347,  347,  347,  347,  347,  347,  347,  348,  348,  348,
      348,  348,  348,  348,  348,  349,  349,  349,  349,  349,
      349,  349,  349,  350,  350,  350,  350,  350,  350,  350,

      350,  351,  351,  351,  351,  351,  351,  351,  351,  352,
      352,  352,  352,  353,  353,  353,  353,  354,  354,  298,
      354,  354,  354,  354,  354,  355,  355,  355,  297,  355,
      355,  355,  355,  356,  356,  356,  356,  357,  357,  357,
      357,  357,  357,  357,  357,  358,  358,  358,  358,  358,
      358,  358,  358,  359,  359,  294,  359,  359,  359,  359,
      359,  360,  360,  293,  360,  360,  360,  360,  360,  361,
      361,  292,  361,  361,  361,  361,  361,  362,  362,  363,
      363,  363,  363,  364,  364,  291,  364,  364,  364,  364,
      364,  365,  365,  365,  365,  365,  365,  365,  365,  366,

      366,  288,  366,  366,  366,  366,  366,  367,  367,  283,
      367,  367,  367,  367,  367,  368,  368,  282,  368,  368,
      368,  368,  368,  369,  369,  369,  369,  369,  369,  369,
      369,  370,  370,  281,  370,  370,  370,  370,  370,  371,
      371,  371,  279,  371,  371,  277,  275,  270,  265,  261,
      260,  259,  254,  251,  249,  248,  246,  243,  228,  222,
      217,  216,  213,  212,  205,  197,  184,  165,  164,  151,
      144,  135,  132,  130,  129,  127,   92,   86,   68,   67,
       63,   58,   56,   51,   31,   27,   26,   25,   24,   15,
       13,    3,  346,  346,  346,  346,  346,  346,  346,  346,

      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346
    } ;

static __IDL__state_type __IDL__last_accepting_state;
static char *__IDL__last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define __IDL_more() __IDL_more_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *__IDL_text;
#line 1 "./lexer.l"
#define INITIAL 0
/***************************************************************************

    lexer.l (IDL lex scanner)

    Copyright (C) 1998, 1999 Andrew T. Veliath

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

    $Id: lexer.l,v 1.72.4.2 2001/09/11 22:25:37 sopwith Exp $

***************************************************************************/
#line 25 "./lexer.l"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "rename.h"
#include "util.h"
#include "parser.h"

#ifdef XP_MAC
#  include <unix.h>
#  define YY_NEVER_INTERACTIVE 1
#endif

/* Eliminate warning */
#define YY_NO_UNPUT 1

#define YY_INPUT(buf,result,the_max_size)	do {				\
	if (__IDL_inputcb == NULL) {						\
		if ((result = fread (buf, 1, the_max_size, __IDL_in)) == YY_NULL &&	\
		    ferror (__IDL_in))						\
			YY_FATAL_ERROR ("input in scanner failed");		\
	} else {								\
		union IDL_input_data data;					\
										\
		data.fill.buffer = buf;						\
		data.fill.max_size = the_max_size;				\
		result = (*__IDL_inputcb) (IDL_INPUT_REASON_FILL, &data,	\
					   __IDL_inputcb_user_data);		\
		if (result < 0)							\
			YY_FATAL_ERROR ("input callback returned failure");	\
	}									\
} while (0)

#define tokreturn(token)			do {	\
	__IDL_prev_token_line = __IDL_cur_token_line;	\
	__IDL_cur_token_line = __IDL_cur_line;		\
	return token;					\
} while (0)

#define SELECT_START				\
	/* Parser driven start conditions */	\
	if (__IDL_flagsi & IDLFP_PROPERTIES)	\
		BEGIN (PROP);			\
	else if (__IDL_flagsi & IDLFP_NATIVE)	\
		BEGIN (NATIVE);			\
	/* Global syntax start conditions */	\
	else if (__IDL_flags & IDLF_XPIDL)	\
		BEGIN (XP);			\
	else if (__IDL_flags & IDLF_CODEFRAGS)	\
		BEGIN (CFRG);

#define SELECT_RESTART				\
	SELECT_START				\
	else					\
		BEGIN (INITIAL);

extern void		__IDL_do_pragma			(const char *s);
static int		count_nl			(const char *s);

#ifdef YYDEBUG
extern int				__IDL_debug;
#endif
int					__IDL_prev_token_line;
int					__IDL_cur_token_line;
static int				warn_underscores;
static char *				codefrag_desc;
static GSList *				codefrag_list;
static GSList *				codefrag_list_tail;
#define XP 1

#define PROP 2

#define NATIVE 3

#define CFRG 4

#define CFRGX 5


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int __IDL_wrap YY_PROTO(( void ));
#else
extern int __IDL_wrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void __IDL_unput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef __IDL_text_ptr
static void __IDL__flex_strncpy YY_PROTO(( char *, __IDL_const char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int __IDL__flex_strlen YY_PROTO(( __IDL_const char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int __IDL_input YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int __IDL__start_stack_ptr = 0;
static int __IDL__start_stack_depth = 0;
static int *__IDL__start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void __IDL__push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void __IDL__pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int __IDL__top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( __IDL_text, __IDL_leng, 1, __IDL_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( __IDL__current_buffer->__IDL__is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( __IDL_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( __IDL_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, __IDL_in )) == 0) \
		  && ferror( __IDL_in ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "__IDL_terminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef __IDL_terminate
#define __IDL_terminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) __IDL__fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int __IDL_lex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after __IDL_text and __IDL_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( __IDL_leng > 0 ) \
		__IDL__current_buffer->__IDL__at_bol = \
				(__IDL_text[__IDL_leng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register __IDL__state_type __IDL__current_state;
	register char *__IDL__cp = NULL, *__IDL__bp = NULL;
	register int __IDL__act;

#line 126 "./lexer.l"


	SELECT_START;


	if ( __IDL__init )
		{
		__IDL__init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! __IDL__start )
			__IDL__start = 1;	/* first start state */

		if ( ! __IDL_in )
			__IDL_in = stdin;

		if ( ! __IDL_out )
			__IDL_out = stdout;

		if ( ! __IDL__current_buffer )
			__IDL__current_buffer =
				__IDL__create_buffer( __IDL_in, YY_BUF_SIZE );

		__IDL__load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		__IDL__cp = __IDL__c_buf_p;

		/* Support of __IDL_text. */
		*__IDL__cp = __IDL__hold_char;

		/* __IDL__bp points to the position in __IDL__ch_buf of the start of
		 * the current run.
		 */
		__IDL__bp = __IDL__cp;

		__IDL__current_state = __IDL__start;
		__IDL__current_state += YY_AT_BOL();
__IDL__match:
		do
			{
			register YY_CHAR __IDL__c = __IDL__ec[YY_SC_TO_UI(*__IDL__cp)];
			if ( __IDL__accept[__IDL__current_state] )
				{
				__IDL__last_accepting_state = __IDL__current_state;
				__IDL__last_accepting_cpos = __IDL__cp;
				}
			while ( __IDL__chk[__IDL__base[__IDL__current_state] + __IDL__c] != __IDL__current_state )
				{
				__IDL__current_state = (int) __IDL__def[__IDL__current_state];
				if ( __IDL__current_state >= 347 )
					__IDL__c = __IDL__meta[(unsigned int) __IDL__c];
				}
			__IDL__current_state = __IDL__nxt[__IDL__base[__IDL__current_state] + (unsigned int) __IDL__c];
			++__IDL__cp;
			}
		while ( __IDL__base[__IDL__current_state] != 893 );

__IDL__find_action:
		__IDL__act = __IDL__accept[__IDL__current_state];
		if ( __IDL__act == 0 )
			{ /* have to back up */
			__IDL__cp = __IDL__last_accepting_cpos;
			__IDL__current_state = __IDL__last_accepting_state;
			__IDL__act = __IDL__accept[__IDL__current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( __IDL__act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*__IDL__cp = __IDL__hold_char;
			__IDL__cp = __IDL__last_accepting_cpos;
			__IDL__current_state = __IDL__last_accepting_state;
			goto __IDL__find_action;

case 1:
YY_RULE_SETUP
#line 130 "./lexer.l"
{
	char *s = __IDL_text + 2;

	while (isspace (*s)) ++s;
	codefrag_desc = g_strdup (s);
	codefrag_list = codefrag_list_tail = NULL;

	if (!(__IDL_flags & IDLF_XPIDL || __IDL_flags & IDLF_CODEFRAGS))
		__IDL_error ("Code fragment syntax not enabled");
	else
		BEGIN (CFRGX);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 142 "./lexer.l"
{
	__IDL_lval.tree = IDL_codefrag_new (codefrag_desc, codefrag_list);
	tokreturn (TOK_CODEFRAG);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 146 "./lexer.l"
{
	char *s;
	GSList *slist;

	s = g_strdup (__IDL_text);
	slist = g_slist_alloc ();
	slist->data = s;

	if (codefrag_list == NULL) {
		codefrag_list = slist;
		codefrag_list_tail = slist;
	} else {
		codefrag_list_tail->next = slist;
		codefrag_list_tail = slist;
	}
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 162 "./lexer.l"
{
	int n;
	char *p = __IDL_text;
	char *s, *t;

	while (isspace (*p) || *p == '#') ++p;
	s = p;
	sscanf (p, "%*6s%n", &n); s += n;
	while (isspace (*s)) ++s;

	t = s + strlen(s) - 1;
	while(isspace(*t) && t > s) *(t--) = '\0'; /* Chomp trailing spaces */

	__IDL_do_pragma (s);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 177 "./lexer.l"
{
	char *starttext;
	char *filename;
	char *filename2;
	int line;

	starttext = __IDL_text;
	while (isspace (*starttext)) ++starttext;
	filename = g_malloc (strlen (starttext) + 1);

	if (sscanf (starttext, "# %d %s", &line, filename) == 2) {

		if (*filename == '"') {
			filename2 = g_strdup (filename + 1);
			filename2[strlen (filename) - 2] = 0;
			g_free (filename);
		} else
			filename2 = filename;

		IDL_file_set (filename2, line);

		g_free (filename2);
	} else
		g_free (filename);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 202 "./lexer.l"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 203 "./lexer.l"
{
	sscanf (__IDL_text, "%" IDL_LL "o", &__IDL_lval.integer);
	tokreturn (TOK_INTEGER);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 207 "./lexer.l"
{
	sscanf (__IDL_text, "%" IDL_LL "u", &__IDL_lval.integer);
	tokreturn (TOK_INTEGER);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 211 "./lexer.l"
{
	sscanf (__IDL_text + 2, "%" IDL_LL "x", &__IDL_lval.integer);
	tokreturn (TOK_INTEGER);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 215 "./lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text);
	tokreturn (TOK_FIXEDP);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 219 "./lexer.l"
{
	__IDL_lval.floatp = atof (__IDL_text);
	tokreturn (TOK_FLOATP);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 223 "./lexer.l"
tokreturn (TOK_FALSE);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 224 "./lexer.l"
tokreturn (TOK_OBJECT);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 225 "./lexer.l"
tokreturn (TOK_TRUE);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 226 "./lexer.l"
tokreturn (TOK_ANY);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 227 "./lexer.l"
tokreturn (TOK_ATTRIBUTE);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 228 "./lexer.l"
tokreturn (TOK_BOOLEAN);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 229 "./lexer.l"
tokreturn (TOK_CASE);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 230 "./lexer.l"
tokreturn (TOK_CHAR);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 231 "./lexer.l"
tokreturn (TOK_CONST);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 232 "./lexer.l"
tokreturn (TOK_CONTEXT);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 233 "./lexer.l"
tokreturn (TOK_DEFAULT);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 234 "./lexer.l"
tokreturn (TOK_DOUBLE);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 235 "./lexer.l"
tokreturn (TOK_ENUM);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 236 "./lexer.l"
tokreturn (TOK_EXCEPTION);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 237 "./lexer.l"
tokreturn (TOK_FIXED);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 238 "./lexer.l"
tokreturn (TOK_FLOAT);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 239 "./lexer.l"
tokreturn (TOK_IN);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 240 "./lexer.l"
tokreturn (TOK_INOUT);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 241 "./lexer.l"
tokreturn (TOK_INTERFACE);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 242 "./lexer.l"
tokreturn (TOK_LONG);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 243 "./lexer.l"
tokreturn (TOK_MODULE);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 244 "./lexer.l"
tokreturn (TOK_NATIVE);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 245 "./lexer.l"
tokreturn (TOK_OCTET);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 246 "./lexer.l"
tokreturn (TOK_ONEWAY);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 247 "./lexer.l"
tokreturn (TOK_OUT);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 248 "./lexer.l"
tokreturn (TOK_RAISES);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 249 "./lexer.l"
tokreturn (TOK_READONLY);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 250 "./lexer.l"
tokreturn (TOK_SEQUENCE);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 251 "./lexer.l"
tokreturn (TOK_SHORT);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 252 "./lexer.l"
tokreturn (TOK_STRING);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 253 "./lexer.l"
tokreturn (TOK_STRUCT);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 254 "./lexer.l"
tokreturn (TOK_SWITCH);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 255 "./lexer.l"
tokreturn (TOK_TYPEDEF);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 256 "./lexer.l"
tokreturn (TOK_UNION);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 257 "./lexer.l"
tokreturn (TOK_UNSIGNED);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 258 "./lexer.l"
tokreturn (TOK_VARARGS);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 259 "./lexer.l"
tokreturn (TOK_VOID);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 260 "./lexer.l"
tokreturn (TOK_WCHAR);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 261 "./lexer.l"
tokreturn (TOK_WSTRING);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 262 "./lexer.l"
tokreturn (TOK_OP_SCOPE);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 263 "./lexer.l"
tokreturn (TOK_OP_SHR);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 264 "./lexer.l"
tokreturn (TOK_OP_SHL);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 265 "./lexer.l"
{
	char *s = g_strdup (__IDL_text);

	/* Get the parenthesized expression (ignoring whitespace) */
	sscanf (__IDL_text, "__declspec %*[(] %[A-Za-z_] %*[)]", s);
	__IDL_lval.str = s;
	__IDL_cur_line += count_nl (__IDL_text);
	tokreturn (TOK_DECLSPEC);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 274 "./lexer.l"
{
	if (__IDL_flags & IDLF_TYPECODES && strcmp (__IDL_text, "TypeCode") == 0)
		tokreturn (TOK_TYPECODE);
	__IDL_lval.str = g_strdup (__IDL_text);
	tokreturn (TOK_IDENT);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 280 "./lexer.l"
{
	__IDL_errorv ("`%s' is not a valid identifier in IDL", __IDL_text);
	__IDL_error ("(Identifiers cannot start with an underscore)");
	__IDL_lval.str = g_strdup (__IDL_text);
	tokreturn (TOK_IDENT);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 286 "./lexer.l"
{
	if (!warn_underscores) {
		__IDL_warningv (IDL_WARNING2,
			   "`%s' underscores within identifiers are discouraged for use "
			   "with C-language IDL mappings", __IDL_text);
		warn_underscores = 1;
	}
	__IDL_lval.str = g_strdup (__IDL_text);
	tokreturn (TOK_IDENT);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 296 "./lexer.l"
{
	__IDL_flagsi &= ~IDLFP_PROPERTIES;
	SELECT_RESTART;
	tokreturn (__IDL_text[0]);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 301 "./lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text);
	tokreturn (TOK_PROP_KEY);
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 305 "./lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text + 1);
	__IDL_lval.str[strlen (__IDL_lval.str) - 1] = 0;
	tokreturn (TOK_PROP_VALUE);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 310 "./lexer.l"
{
	__IDL_flagsi &= ~IDLFP_NATIVE;
	__IDL_lval.str = g_strdup (__IDL_text);
	__IDL_lval.str[strlen (__IDL_lval.str) - 1] = 0;
	tokreturn (TOK_NATIVE_TYPE);
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 316 "./lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text + 1);
	__IDL_lval.str[strlen (__IDL_text) - 2] = 0;
	tokreturn (TOK_SQSTRING);
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 321 "./lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text + 1);
	__IDL_lval.str[strlen (__IDL_text) - 2] = 0;
	tokreturn (TOK_DQSTRING);
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 326 "./lexer.l"
++__IDL_cur_line;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 327 "./lexer.l"
;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 328 "./lexer.l"
{
	int c;

	while (1) {
		while ((c = input ()) != '*' && c != EOF)
			if (c == '\n') ++__IDL_cur_line;
		if (c == '*') {
			while ((c = input ()) == '*') ;
			if (c == '/') break;
		}
		if (c == '\n') ++__IDL_cur_line;
		if (c == EOF) {
			__IDL_warning (IDL_WARNING1, "End of file in comment");
			break;
		}
	}
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 345 "./lexer.l"
tokreturn (__IDL_text[0]);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 347 "./lexer.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(XP):
case YY_STATE_EOF(PROP):
case YY_STATE_EOF(NATIVE):
case YY_STATE_EOF(CFRG):
case YY_STATE_EOF(CFRGX):
	__IDL_terminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int __IDL__amount_of_matched_text = (int) (__IDL__cp - __IDL_text_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*__IDL__cp = __IDL__hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( __IDL__current_buffer->__IDL__buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed __IDL_in at a new source and called
			 * __IDL_lex().  If so, then we have to assure
			 * consistency between __IDL__current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			__IDL__n_chars = __IDL__current_buffer->__IDL__n_chars;
			__IDL__current_buffer->__IDL__input_file = __IDL_in;
			__IDL__current_buffer->__IDL__buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for __IDL__c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since __IDL__c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( __IDL__c_buf_p <= &__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars] )
			{ /* This was really a NUL. */
			__IDL__state_type __IDL__next_state;

			__IDL__c_buf_p = __IDL_text_ptr + __IDL__amount_of_matched_text;

			__IDL__current_state = __IDL__get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * __IDL__get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			__IDL__next_state = __IDL__try_NUL_trans( __IDL__current_state );

			__IDL__bp = __IDL_text_ptr + YY_MORE_ADJ;

			if ( __IDL__next_state )
				{
				/* Consume the NUL. */
				__IDL__cp = ++__IDL__c_buf_p;
				__IDL__current_state = __IDL__next_state;
				goto __IDL__match;
				}

			else
				{
				__IDL__cp = __IDL__c_buf_p;
				goto __IDL__find_action;
				}
			}

		else switch ( __IDL__get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				__IDL__did_buffer_switch_on_eof = 0;

				if ( __IDL_wrap() )
					{
					/* Note: because we've taken care in
					 * __IDL__get_next_buffer() to have set up
					 * __IDL_text, we can now set up
					 * __IDL__c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					__IDL__c_buf_p = __IDL_text_ptr + YY_MORE_ADJ;

					__IDL__act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! __IDL__did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				__IDL__c_buf_p =
					__IDL_text_ptr + __IDL__amount_of_matched_text;

				__IDL__current_state = __IDL__get_previous_state();

				__IDL__cp = __IDL__c_buf_p;
				__IDL__bp = __IDL_text_ptr + YY_MORE_ADJ;
				goto __IDL__match;

			case EOB_ACT_LAST_MATCH:
				__IDL__c_buf_p =
				&__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars];

				__IDL__current_state = __IDL__get_previous_state();

				__IDL__cp = __IDL__c_buf_p;
				__IDL__bp = __IDL_text_ptr + YY_MORE_ADJ;
				goto __IDL__find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of __IDL_lex */


/* __IDL__get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int __IDL__get_next_buffer()
	{
	register char *dest = __IDL__current_buffer->__IDL__ch_buf;
	register char *source = __IDL_text_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( __IDL__c_buf_p > &__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( __IDL__current_buffer->__IDL__fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( __IDL__c_buf_p - __IDL_text_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (__IDL__c_buf_p - __IDL_text_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( __IDL__current_buffer->__IDL__buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		__IDL__current_buffer->__IDL__n_chars = __IDL__n_chars = 0;

	else
		{
		int num_to_read =
			__IDL__current_buffer->__IDL__buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = __IDL__current_buffer;

			int __IDL__c_buf_p_offset =
				(int) (__IDL__c_buf_p - b->__IDL__ch_buf);

			if ( b->__IDL__is_our_buffer )
				{
				int new_size = b->__IDL__buf_size * 2;

				if ( new_size <= 0 )
					b->__IDL__buf_size += b->__IDL__buf_size / 8;
				else
					b->__IDL__buf_size *= 2;

				b->__IDL__ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					__IDL__flex_realloc( (void *) b->__IDL__ch_buf,
							 b->__IDL__buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->__IDL__ch_buf = 0;

			if ( ! b->__IDL__ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			__IDL__c_buf_p = &b->__IDL__ch_buf[__IDL__c_buf_p_offset];

			num_to_read = __IDL__current_buffer->__IDL__buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&__IDL__current_buffer->__IDL__ch_buf[number_to_move]),
			__IDL__n_chars, num_to_read );

		__IDL__current_buffer->__IDL__n_chars = __IDL__n_chars;
		}

	if ( __IDL__n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			__IDL_restart( __IDL_in );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			__IDL__current_buffer->__IDL__buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	__IDL__n_chars += number_to_move;
	__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars] = YY_END_OF_BUFFER_CHAR;
	__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	__IDL_text_ptr = &__IDL__current_buffer->__IDL__ch_buf[0];

	return ret_val;
	}


/* __IDL__get_previous_state - get the state just before the EOB char was reached */

static __IDL__state_type __IDL__get_previous_state()
	{
	register __IDL__state_type __IDL__current_state;
	register char *__IDL__cp;

	__IDL__current_state = __IDL__start;
	__IDL__current_state += YY_AT_BOL();

	for ( __IDL__cp = __IDL_text_ptr + YY_MORE_ADJ; __IDL__cp < __IDL__c_buf_p; ++__IDL__cp )
		{
		register YY_CHAR __IDL__c = (*__IDL__cp ? __IDL__ec[YY_SC_TO_UI(*__IDL__cp)] : 1);
		if ( __IDL__accept[__IDL__current_state] )
			{
			__IDL__last_accepting_state = __IDL__current_state;
			__IDL__last_accepting_cpos = __IDL__cp;
			}
		while ( __IDL__chk[__IDL__base[__IDL__current_state] + __IDL__c] != __IDL__current_state )
			{
			__IDL__current_state = (int) __IDL__def[__IDL__current_state];
			if ( __IDL__current_state >= 347 )
				__IDL__c = __IDL__meta[(unsigned int) __IDL__c];
			}
		__IDL__current_state = __IDL__nxt[__IDL__base[__IDL__current_state] + (unsigned int) __IDL__c];
		}

	return __IDL__current_state;
	}


/* __IDL__try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = __IDL__try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static __IDL__state_type __IDL__try_NUL_trans( __IDL__state_type __IDL__current_state )
#else
static __IDL__state_type __IDL__try_NUL_trans( __IDL__current_state )
__IDL__state_type __IDL__current_state;
#endif
	{
	register int __IDL__is_jam;
	register char *__IDL__cp = __IDL__c_buf_p;

	register YY_CHAR __IDL__c = 1;
	if ( __IDL__accept[__IDL__current_state] )
		{
		__IDL__last_accepting_state = __IDL__current_state;
		__IDL__last_accepting_cpos = __IDL__cp;
		}
	while ( __IDL__chk[__IDL__base[__IDL__current_state] + __IDL__c] != __IDL__current_state )
		{
		__IDL__current_state = (int) __IDL__def[__IDL__current_state];
		if ( __IDL__current_state >= 347 )
			__IDL__c = __IDL__meta[(unsigned int) __IDL__c];
		}
	__IDL__current_state = __IDL__nxt[__IDL__base[__IDL__current_state] + (unsigned int) __IDL__c];
	__IDL__is_jam = (__IDL__current_state == 346);

	return __IDL__is_jam ? 0 : __IDL__current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void __IDL_unput( int c, register char *__IDL__bp )
#else
static void __IDL_unput( c, __IDL__bp )
int c;
register char *__IDL__bp;
#endif
	{
	register char *__IDL__cp = __IDL__c_buf_p;

	/* undo effects of setting up __IDL_text */
	*__IDL__cp = __IDL__hold_char;

	if ( __IDL__cp < __IDL__current_buffer->__IDL__ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = __IDL__n_chars + 2;
		register char *dest = &__IDL__current_buffer->__IDL__ch_buf[
					__IDL__current_buffer->__IDL__buf_size + 2];
		register char *source =
				&__IDL__current_buffer->__IDL__ch_buf[number_to_move];

		while ( source > __IDL__current_buffer->__IDL__ch_buf )
			*--dest = *--source;

		__IDL__cp += (int) (dest - source);
		__IDL__bp += (int) (dest - source);
		__IDL__current_buffer->__IDL__n_chars =
			__IDL__n_chars = __IDL__current_buffer->__IDL__buf_size;

		if ( __IDL__cp < __IDL__current_buffer->__IDL__ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--__IDL__cp = (char) c;


	__IDL_text_ptr = __IDL__bp;
	__IDL__hold_char = *__IDL__cp;
	__IDL__c_buf_p = __IDL__cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int __IDL_input()
#else
static int input()
#endif
	{
	int c;

	*__IDL__c_buf_p = __IDL__hold_char;

	if ( *__IDL__c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* __IDL__c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( __IDL__c_buf_p < &__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars] )
			/* This was really a NUL. */
			*__IDL__c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = __IDL__c_buf_p - __IDL_text_ptr;
			++__IDL__c_buf_p;

			switch ( __IDL__get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because __IDL__g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					__IDL_restart( __IDL_in );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( __IDL_wrap() )
						return EOF;

					if ( ! __IDL__did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return __IDL_input();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					__IDL__c_buf_p = __IDL_text_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) __IDL__c_buf_p;	/* cast for 8-bit char's */
	*__IDL__c_buf_p = '\0';	/* preserve __IDL_text */
	__IDL__hold_char = *++__IDL__c_buf_p;

	__IDL__current_buffer->__IDL__at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void __IDL_restart( FILE *input_file )
#else
void __IDL_restart( input_file )
FILE *input_file;
#endif
	{
	if ( ! __IDL__current_buffer )
		__IDL__current_buffer = __IDL__create_buffer( __IDL_in, YY_BUF_SIZE );

	__IDL__init_buffer( __IDL__current_buffer, input_file );
	__IDL__load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void __IDL__switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void __IDL__switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( __IDL__current_buffer == new_buffer )
		return;

	if ( __IDL__current_buffer )
		{
		/* Flush out information for old buffer. */
		*__IDL__c_buf_p = __IDL__hold_char;
		__IDL__current_buffer->__IDL__buf_pos = __IDL__c_buf_p;
		__IDL__current_buffer->__IDL__n_chars = __IDL__n_chars;
		}

	__IDL__current_buffer = new_buffer;
	__IDL__load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (__IDL_wrap()) processing, but the only time this flag
	 * is looked at is after __IDL_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	__IDL__did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void __IDL__load_buffer_state( void )
#else
void __IDL__load_buffer_state()
#endif
	{
	__IDL__n_chars = __IDL__current_buffer->__IDL__n_chars;
	__IDL_text_ptr = __IDL__c_buf_p = __IDL__current_buffer->__IDL__buf_pos;
	__IDL_in = __IDL__current_buffer->__IDL__input_file;
	__IDL__hold_char = *__IDL__c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE __IDL__create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE __IDL__create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) __IDL__flex_alloc( sizeof( struct __IDL__buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in __IDL__create_buffer()" );

	b->__IDL__buf_size = size;

	/* __IDL__ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->__IDL__ch_buf = (char *) __IDL__flex_alloc( b->__IDL__buf_size + 2 );
	if ( ! b->__IDL__ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in __IDL__create_buffer()" );

	b->__IDL__is_our_buffer = 1;

	__IDL__init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void __IDL__delete_buffer( YY_BUFFER_STATE b )
#else
void __IDL__delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == __IDL__current_buffer )
		__IDL__current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->__IDL__is_our_buffer )
		__IDL__flex_free( (void *) b->__IDL__ch_buf );

	__IDL__flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void __IDL__init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void __IDL__init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	__IDL__flush_buffer( b );

	b->__IDL__input_file = file;
	b->__IDL__fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->__IDL__is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->__IDL__is_interactive = 0;
#else
	b->__IDL__is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void __IDL__flush_buffer( YY_BUFFER_STATE b )
#else
void __IDL__flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->__IDL__n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->__IDL__ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->__IDL__ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->__IDL__buf_pos = &b->__IDL__ch_buf[0];

	b->__IDL__at_bol = 1;
	b->__IDL__buffer_status = YY_BUFFER_NEW;

	if ( b == __IDL__current_buffer )
		__IDL__load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE __IDL__scan_buffer( char *base, __IDL__size_t size )
#else
YY_BUFFER_STATE __IDL__scan_buffer( base, size )
char *base;
__IDL__size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) __IDL__flex_alloc( sizeof( struct __IDL__buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in __IDL__scan_buffer()" );

	b->__IDL__buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->__IDL__buf_pos = b->__IDL__ch_buf = base;
	b->__IDL__is_our_buffer = 0;
	b->__IDL__input_file = 0;
	b->__IDL__n_chars = b->__IDL__buf_size;
	b->__IDL__is_interactive = 0;
	b->__IDL__at_bol = 1;
	b->__IDL__fill_buffer = 0;
	b->__IDL__buffer_status = YY_BUFFER_NEW;

	__IDL__switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE __IDL__scan_string( __IDL_const char *__IDL__str )
#else
YY_BUFFER_STATE __IDL__scan_string( __IDL__str )
__IDL_const char *__IDL__str;
#endif
	{
	int len;
	for ( len = 0; __IDL__str[len]; ++len )
		;

	return __IDL__scan_bytes( __IDL__str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE __IDL__scan_bytes( __IDL_const char *bytes, int len )
#else
YY_BUFFER_STATE __IDL__scan_bytes( bytes, len )
__IDL_const char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	__IDL__size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) __IDL__flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in __IDL__scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = __IDL__scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in __IDL__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->__IDL__is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void __IDL__push_state( int new_state )
#else
static void __IDL__push_state( new_state )
int new_state;
#endif
	{
	if ( __IDL__start_stack_ptr >= __IDL__start_stack_depth )
		{
		__IDL__size_t new_size;

		__IDL__start_stack_depth += YY_START_STACK_INCR;
		new_size = __IDL__start_stack_depth * sizeof( int );

		if ( ! __IDL__start_stack )
			__IDL__start_stack = (int *) __IDL__flex_alloc( new_size );

		else
			__IDL__start_stack = (int *) __IDL__flex_realloc(
					(void *) __IDL__start_stack, new_size );

		if ( ! __IDL__start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	__IDL__start_stack[__IDL__start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void __IDL__pop_state()
	{
	if ( --__IDL__start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(__IDL__start_stack[__IDL__start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int __IDL__top_state()
	{
	return __IDL__start_stack[__IDL__start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void __IDL__fatal_error( __IDL_const char msg[] )
#else
static void __IDL__fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine __IDL_less() so it works in section 3 code. */

#undef __IDL_less
#define __IDL_less(n) \
	do \
		{ \
		/* Undo effects of setting up __IDL_text. */ \
		__IDL_text[__IDL_leng] = __IDL__hold_char; \
		__IDL__c_buf_p = __IDL_text + n; \
		__IDL__hold_char = *__IDL__c_buf_p; \
		*__IDL__c_buf_p = '\0'; \
		__IDL_leng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef __IDL_text_ptr
#ifdef YY_USE_PROTOS
static void __IDL__flex_strncpy( char *s1, __IDL_const char *s2, int n )
#else
static void __IDL__flex_strncpy( s1, s2, n )
char *s1;
__IDL_const char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int __IDL__flex_strlen( __IDL_const char *s )
#else
static int __IDL__flex_strlen( s )
__IDL_const char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *__IDL__flex_alloc( __IDL__size_t size )
#else
static void *__IDL__flex_alloc( size )
__IDL__size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *__IDL__flex_realloc( void *ptr, __IDL__size_t size )
#else
static void *__IDL__flex_realloc( ptr, size )
void *ptr;
__IDL__size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void __IDL__flex_free( void *ptr )
#else
static void __IDL__flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	__IDL_lex();
	return 0;
	}
#endif
#line 347 "./lexer.l"


void __IDL_lex_init (void)
{
	__IDL_inputcb = NULL;
	__IDL_cur_line = 1;
	__IDL_cur_token_line = 0;
	__IDL_prev_token_line = 0;
	__IDL_cur_filename = NULL;
	__IDL_cur_fileinfo = NULL;
	warn_underscores = 0;
}

void __IDL_lex_cleanup (void)
{
	__IDL_cur_filename = NULL;
	YY_NEW_FILE;
}

int __IDL_wrap (void)
{
	return 1;
}

static int count_nl (const char *s)
{
	int i;

	for (i = 0;
	     (s = strchr (s, '\n')) != NULL;
	     ++s, ++i) ;

	return i;
}

/*
 * Local variables:
 * mode: C
 * c-basic-offset: 8
 * tab-width: 8
 * indent-tabs-mode: t
 * End:
 */
