// -*- c++ -*-
//  Generated by gtkmmproc from ./applet-main.gen_h -- DO NOT MODIFY!
#ifndef _GNOMEMM_APPLET_MAIN_H
#define _GNOMEMM_APPLET_MAIN_H

/* $Id: applet-main.gen_h,v 1.5 2002/01/07 20:16:01 cactus Exp $ -*- c++ -*- */
// -*- C++ -*- // this is for the .gen_h, I realize gensig puts one in

/* applet_main.h
 *
 * Copyright (C) 1999-2001 Gergõ ÉRDI <cactus@cactus.rulez.org>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include <gtk--/main.h>
#include <applet-widget.h>


namespace Gnome
{
class Applet_Main : public Gtk::Main
{
public:

  Applet_Main(const Gtk::string &app_id,
	      const Gtk::string &app_version,
	      int argc, char **argv,
	      struct poptOption *options = 0,
	      unsigned int flags = 0,
	      poptContext *return_ctx = 0);

  ~Applet_Main();

  static void quit_panel();

  //: How many applets are running?
  static int get_applet_count() {
    return applet_widget_get_applet_count();};

protected:
  Applet_Main();

  virtual void run_impl();
  virtual void quit_impl();
};

}

#endif
