.\"Created with GNOME Manpages Editor
.\"http://gmanedit.sourceforge.net
.\"Sergio Rua <srua@gpul.org>
.\"
.TH oafd 1 "12 Oct 2001" "GNOME" "The GNOME Project"

.SH NAME
oafd \- the GNOME Object Activation Daemon.

.SH SYNOPSIS
.B oafd
.RI [ options ]
.br

.SH DESCRIPTION
The
.I oafd
daemon provides a simple naming-service wrapper for GNOME
applicatinos that are using CORBA, Orbit, OAF and/or Bonobo.

.PP
\fBoafd\fP is normally started automatically when the gnome 
desktop is started.

.SH OPTIONS
.B
.IP --ac-activate
Serve as an ActivationContext (default is as an ObjectDirectory only)

.IP --ior-output-fd=FD
File descriptor to write IOR to

.IP --od-domain=DOMAIN
Domain of ObjectDirectory

.IP --od-source-dir=DIRECTORY
Directory to read .oafinfo files from

.SH AUTHOR
The Gnome Project
