.\" idetool.8 - IDE Tool
.\" Copyright 2001  Jochen Voss
.TH idetool 8 "Apr 21 2001" "gnome-utils 1.4.0"
.SH NAME
idetool \- view properties and settings of IDE drives
.SH SYNOPSIS
.B idetool
.sp
or select
.B IDE Device Tool
from the
.B Utilities
submenu of the Main Menu.
.SH DESCRIPTION
.B IDE Tool
is a tool for viewing and tuning the properties and settings of IDE
drives, such as IDE hard drives and CDROMs. The hard drive properties
which IDE Tool shows include the model, geometry, and cache. It allows
you to control drive configuration such as whether it uses DMA and IRQ
unmask.

You must be root to use this utility.

For full documentation see the
.B IDE Tool
online help.

.SH AUTHOR
.B IDE Tool
was written by Alan Cox (<alan@lxorguk.ukuu.org.uk>).

This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.

.SH SEE ALSO
.BR hdparm (8)
