interface quux {
	attribute double wibble;
	long duplicate();
};

module ORBitTest {
	interface foo {
		attribute long wibble;
	};

	interface bar:foo {
		long dummy();
		short duplicate();
	};
};

module AnotherTest {
	interface foo: ORBitTest::foo, ORBitTest::bar {
		long fooDummy();
	};

	interface baz: foo, ::quux {
		long bazDummy();
	};
};
