.\" 
.\" gnome-exe-handler manual page.
.\" (C) Ximian, Inc http://www.ximian.com
.\" 
.\"
.TH GNOME 1 "GNOME 1.0"
.SH NAME
gnome-exe-handler \- GNOME executable Mime type Handler.
.SH SYNOPSIS
.PP
.B gnome-exe-handler file1 file2...
.SH DESCRIPTION
The \fIgnome-exe-handler\fP program is invoked by applications that
try to launch executables in Unix but do not have the execution
permission bit set.  The are classified as ELF or A.OUT executables by
the MIME system.
.PP
.I gnome-exe-handler
Would let the user double click on an application and if the user
confirms the action, change the permissions automatically for him and
then launch the application.  This is particulary useful when
downloading software from the network, as Unix will not transfer the
execution permissions.  This simplifies the number of steps that a
novice user has to take to run software from the net.
.SH AUTHOR
.I gnome-exe-handler 
was written by Miguel de Icaza (miguel@gnu.org)
.SH SEE ALSO
.BR gnome(1), 
.BR gnome-vfs-mime(5), 
.BR nautilus(1), 
.BR mc(1)
.SH BUGS
Report bugs to bugzilla.gnome.org, against module `gnome-utils'
