.\" gsearchtool.1 - GNOME Search Tool
.\" Copyright 2001  Jochen Voss
.TH gsearchtool 1 "Apr 16 2001" "gnome-utils 1.4.0"
.SH NAME
gsearchtool \- the GNOME Search Tool
.SH SYNOPSIS
.B gsearchtool
.sp
or select
.B GNOME Search Tool
from the
.B Utilities
submenu of the Main Menu.
.SH DESCRIPTION
.B GNOME Search Tool
is a utility for searching files on your system. It can perform many
types of search: by filename, by modification date, by file contents,
etc.

For full documentation see the
.B GNOME Search Tool
gsearchtool online help.

.SH AUTHOR
.B GNOME Search Tool
was written by George Lebl (<jirka@5z.com>).

This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.

.SH SEE ALSO
.BR find (1)
.BR locate (1)
