.\" gw.1 - GNOME version of w
.\" Copyright 2001  Jochen Voss
.TH gw 1 "Apr 21 2001" "gnome-utils 1.4.0"
.SH NAME
gw \- GNOME version of w
.SH SYNOPSIS
.B gw
.sp
or select
.B User Listing
from the
.B System
submenu of the Main Menu.
.SH DESCRIPTION
.B Gw
displays a listing of all the users currently logged onto your
machine, along with information about what they're up to.  It also
gives you the ability to communicate with them.

For full documentation see the
.B Gw
online help.

.SH AUTHOR
.B Gw
was written by Havoc Pennington (<hp@redhat.com>).

This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.

.SH SEE ALSO
.BR w (1),
.BR who (1),
.BR talk (1)
