.\" gdiskfree.1 - GNOME DiskFree
.\" Copyright 2001  Jochen Voss
.TH gdiskfree 1 "Apr 7 2001" "gnome-utils 1.4.0"
.SH NAME
gdiskfree \- GNOME utility to monitor disk space usage
.SH SYNOPSIS
.B gdiskfree
.sp
or select
.B GNOME DiskFree
from the
.B Utilities
submenu of the Main Menu.
.SH DESCRIPTION
.B GNOME DiskFree
is a program for monitoring disk usage on your computer.

For full documentation see the
.B GNOME DiskFree
online help.

.SH AUTHOR
.B GNOME DiskFree
was written by Gregory McLean (<gregm@comstar.net>).

This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.

.SH SEE ALSO
.BR df (1)
