.\" gfloppy.1 - a simple floppy formatter
.\" Copyright 2001  Jochen Voss
.TH gfloppy 1 "Apr 7 2001" "gnome-utils 1.4.0"
.SH NAME
gfloppy \- a simple floppy formatter for the GNOME
.SH SYNOPSIS
.B gfloppy
.sp
or select
.B gfloppy
from the
.B Utilities
submenu of the Main Menu.
.sp
or right click on the floppy icon on your desktop and select
.B Format Floppy
.SH DESCRIPTION
.B GFloppy
is a simple floppy formatter for Linux.  It supports the DOS format
and the ext2 file system.  In order to create DOS floppies you need to
have the mtools package installed.
.P
For full documentation see the
.B GFloppy
online help.
.SH OPTIONS
In addition to the standard GNOME options
.B GFloppy
supports the following one.
.TP
.BI \-\-device= DEVICE
The device to format (instead of
.IR /dev/fd0 ).
.SH AUTHOR
.B GFloppy
was written by Jonathan Blandford (<jrb@redhat.com>).
.P
This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.
.SH SEE ALSO
.BR mformat (1),
.BR fdformat (8),
.BR superformat (8),
and the
.B fdutils
info manual
