/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "empty.h"

void
_ORBIT_skel_Empty_doNothing(POA_Empty * _ORBIT_servant,
			    GIOPRecvBuffer * _ORBIT_recv_buffer,
			    CORBA_Environment * ev,
			    void (*_impl_doNothing) (PortableServer_Servant
						     _servant,
						     CORBA_Environment * ev))
{
   _impl_doNothing(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
static ORBitSkeleton
get_skel_Empty(POA_Empty * servant,
	       GIOPRecvBuffer * _ORBIT_recv_buffer, gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'd':
	if (strcmp((opname + 1), "oNothing"))
	   break;
	*impl = (gpointer) servant->vepv->Empty_epv->doNothing;
	return (ORBitSkeleton) _ORBIT_skel_Empty_doNothing;
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_Empty(CORBA_Object obj, POA_Empty * servant)
{
   obj->vepv[Empty__classid] = servant->vepv->Empty_epv;
}

void
POA_Empty__init(PortableServer_Servant servant, CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_Empty, "IDL:Empty:1.0",
(ORBit_local_objref_init) & init_local_objref_Empty };
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!Empty__classid)
      Empty__classid = ORBit_register_class(&class_info);
}

void
POA_Empty__fini(PortableServer_Servant servant, CORBA_Environment * env)
{
   PortableServer_ServantBase__fini(servant, env);
}
