/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "gtcd.h"

#if ( (TC_IMPL_TC_GNOME_GTcd_0 == 'g') \
&& (TC_IMPL_TC_GNOME_GTcd_1 == 't') \
&& (TC_IMPL_TC_GNOME_GTcd_2 == 'c') \
&& (TC_IMPL_TC_GNOME_GTcd_3 == 'd') \
) && !defined(TC_DEF_TC_GNOME_GTcd)
#define TC_DEF_TC_GNOME_GTcd 1
const struct CORBA_TypeCode_struct TC_GNOME_GTcd_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "GTcd", "IDL:GNOME/GTcd:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long GNOME_GTcd__classid = 0;
