/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "gtcd.h"

void
_ORBIT_skel_GNOME_GTcd_open_new_cd(POA_GNOME_GTcd * _ORBIT_servant,
				   GIOPRecvBuffer * _ORBIT_recv_buffer,
				   CORBA_Environment * ev,
				   void (*_impl_open_new_cd)
				   (PortableServer_Servant _servant,
				    CORBA_Environment * ev))
{
   _impl_open_new_cd(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
static ORBitSkeleton
get_skel_GNOME_GTcd(POA_GNOME_GTcd * servant,
		    GIOPRecvBuffer * _ORBIT_recv_buffer, gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'o':
	if (strcmp((opname + 1), "pen_new_cd"))
	   break;
	*impl = (gpointer) servant->vepv->GNOME_GTcd_epv->open_new_cd;
	return (ORBitSkeleton) _ORBIT_skel_GNOME_GTcd_open_new_cd;
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_GNOME_GTcd(CORBA_Object obj, POA_GNOME_GTcd * servant)
{
   obj->vepv[GNOME_GTcd__classid] = servant->vepv->GNOME_GTcd_epv;
}

void
POA_GNOME_GTcd__init(PortableServer_Servant servant, CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_GNOME_GTcd, "IDL:GNOME/GTcd:1.0",
(ORBit_local_objref_init) & init_local_objref_GNOME_GTcd };
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!GNOME_GTcd__classid)
      GNOME_GTcd__classid = ORBit_register_class(&class_info);
}

void
POA_GNOME_GTcd__fini(PortableServer_Servant servant, CORBA_Environment * env)
{
   PortableServer_ServantBase__fini(servant, env);
}
