.\" gshutdown.8 - GNOME shutdown untility
.\" Copyright 2001  Jochen Voss
.TH gshutdown 8 "Apr 16 2001" "gnome-utils 1.4.0"
.SH NAME
gshutdown \- reboot or shutdown your machine
.SH SYNOPSIS
.B gshutdown
.sp
or select
.B Shut Down or Reboot
from the
.B System
submenu of the Main Menu.
.SH DESCRIPTION
.B Gshutdown
is a program for shutting down your computer.
It has support for changing the systems runlevel, too.
You must be root to use this program.

For full documentation see the
.B Gshutdown
online help.

.SH AUTHOR
.B Gshutdown
was written by Havoc Pennington (<hp@redhat.com>).

This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.

.SH SEE ALSO
.BR shutdown (8),
.BR halt (8),
.BR reboot (8),
.BR telinit (8)
