.TH SCROLLKEEPER-CONFIG 8 "Nov 08, 2000" "scrollkeeper"
.SH NAME
scrollkeeper-config \- print ScrollKeeper configuration information
.SH SYNOPSIS
.B "scrollkeeper-config"
[--help]
[--version]
[--prefix]
[--localstatedir]
[--pkglocalstatedir]
[--pkgdatadir]
[--omfdir]

.SH DESCRIPTION
This prints out various ScrollKeeper configuration information. It
is useful for application building and packaging procedures.

.SH OPTIONS
.TP
.I \--help 
Show usage (help) information.
.TP
.I \--version
Show version number.
.TP
.I \--prefix
Outputs the prefix used to install Scrollkeeper. 
.TP
.I \--localstatedir
Outputs the localstatedir used to install Scrollkeeper. 
.TP
.I \--pkglocalstatedir
Outputs pkglocalstatedir. This is the directory under localstatedir
where ScrollKeeper keeps its database.
.TP
.I \--pkgdatadir
Outputs pkgdatadir. This is the directory under datadir
where ScrollKeeper keeps its non-variable (ie. non-database) 
files.
.TP
.I \--omfdir
Directory where ScrollKeeper looks for OMF files.


.SH AUTHOR
Laszlo Kovacs and Dan Mueth.

.SH SEE ALSO
scrollkeeper-update(8), scrollkeeper-preinstall(8), scrollkeeper-rebuilddb(8)
