.TH SCROLLKEEPER-PREINSTALL 8 "Nov 07, 2000" "scrollkeeper"
.SH NAME
scrollkeeper-preinstall \- generate on OMF file, based on an existing
OMF file, which has the correct URL for a document
.SH SYNOPSIS
.B "scrollkeeper-preinstall"
.IR url 
.IR input-omf-file 
.IR output-omf-file
.SH DESCRIPTION
scrollkeeper-preinstall creates the OMF file 
.IR output-omf-file 
by reading the given existing 
OMF file 
.IR input-omf-file 
and replacing the URL for a resource (typically a document) with
the URL given by
.IR url .
This is typically done as part of the build process for 
an application, since the actual location that a document 
is installed is not known until the application is built.

If 
.I output-omf-file
is specified with a path, and that path does not exist, 
the path is created.

The 
.IR url
is typically the "file:" URI followed by the absolute path
to a document which is (or will be) installed. 
(eg. "file:/usr/doc/scrollkeeper/scrollkeeper.sgml") 

.SH AUTHOR
Laszlo Kovacs and Dan Mueth.

.SH SEE ALSO
scrollkeeper-update(8), scrollkeeper-rebuilddb(8), scrollkeeper-config(8)
