.TH SCROLLKEEPER-REBUILDDB 8 "Nov 07, 2000" "scrollkeeper"
.SH NAME
scrollkeeper-rebuilddb \- rebuild the scrollkeeper document catalog database
.SH SYNOPSIS
.B "scrollkeeper-rebuilddb"
[-p  
.IR path]

.SH DESCRIPTION
This rebuilds the scrollkeeper database from the original OMF metadata
files and documents.  Under normal situations, this tool is not
necessary.  It is useful however if the database become corrupt, which
could be caused by interruption of scrollkeeper during an update of
the database.

.SH OPTIONS
.TP
.I \-p \fIpath\fP 
Use \fIpath\fP as the scrollkeeper database directory.

.SH AUTHOR
Laszlo Kovacs and Dan Mueth.

.SH SEE ALSO
scrollkeeper-update(8), scrollkeeper-preinstall(8), scrollkeeper-config(8)
